### ISSUE TITLE
How would someone handle Phantom Process died?

### ISSUE THREAD

**Issue by mato75** [johntitus/node-horseman#106]
I would like to handle this error:

    Unhandled rejection HeadlessError: Phantom Process died
    at poll_func (/vagrant/node_modules/node-phantom-simple/node-phantom-simple.js:586:10)
    at /vagrant/node_modules/node-phantom-simple/node-phantom-simple.js:54:7
    at ClientRequest.<anonymous> (/vagrant/node_modules/node-phantom-simple/node-phantom-simple.js:499:11)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at Socket.socketErrorListener (_http_client.js:262:9)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at emitErrorNT (net.js:1255:8)
    at nextTickCallbackWith2Args (node.js:474:9)
    at process._tickCallback (node.js:388:17)

Ready wrapper:

     _ready: function (res, rej) {
        var that = this;
        return this.ready
            .then(res)
            .catch(function (err) {
                return new Promise(function(resolve, reject) {
                    console.log('Page Error', err);
                    reject({ type: 'page-evaluation-error' });
                });
            });
    },

When reject with type: 'page-evaluation-error' is called, I am getting this issue:

    Unhandled rejection Error: [object Object]
    at Object.ensureErrorObject (/vagrant/node_modules/bluebird/js/main/util.js:261:20)
    at Promise._rejectCallback (/vagrant/node_modules/bluebird/js/main/promise.js:469:22)
    at /vagrant/node_modules/bluebird/js/main/promise.js:486:17
    at /vagrant/server/city/officer.js:183:21
    at tryCatcher (/vagrant/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._resolveFromResolver (/vagrant/node_modules/bluebird/js/main/promise.js:480:31)
    at new Promise (/vagrant/node_modules/bluebird/js/main/promise.js:70:37)
    at /vagrant/server/city/officer.js:181:24
    at tryCatcher (/vagrant/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/vagrant/node_modules/bluebird/js/main/promise.js:507:31)
    at Promise._settlePromiseAt (/vagrant/node_modules/bluebird/js/main/promise.js:581:18)
    at Async._drainQueue (/vagrant/node_modules/bluebird/js/main/async.js:128:12)
    at Async._drainQueues (/vagrant/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/vagrant/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)

Any suggestions?

**Comment by awlayton** [comment]
If the phantom process is dead, you probably have to make a new Horseman instance. The old one won't work anymore.

**Comment by mato75** [comment]
Yes I know, that is what I would like to do, but this stops NodeJS process, so I cannot even create a new instance.

       .catch(function (err) {
             // clear current phantom and ready, and create new
       });

**Comment by awlayton** [comment]
You could try surrounding your horseman chain in a try catch, e.g.,
```javascript
try {
    horseman.open()
        .whatever()...
} catch (err) {
}
```

Though it probably should be rejecting the Promise of the chain and not throwing synchronously... There might be a bug.

**Comment by mato75** [comment]
I opened this issue at node-phantomjs-simple, if you would like to comment:

https://github.com/baudehlo/node-phantom-simple/issues/110

**Comment by awlayton** [comment]
It might be a bug there too, but node-phantom-simple is not Promise based. Somewhere horseman must not be using Promises properly, or else this would only result in a rejection and not throw.

**Comment by mato75** [comment]
Tried try/catch around horseman, but still it cancels nodejs process.

**Comment by awlayton** [comment]
Hm... then maybe there isn't a bug in horseman.

**Comment by mato75** [comment]
This issue occurs also:

    Unhandled rejection HeadlessError: Request() error evaluating createPage() call: Error: socket hang up
    at ClientRequest.<anonymous> (/vagrant/node_modules/node-phantom-simple/node-phantom-simple.js:504:18)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at Socket.socketOnEnd (_http_client.js:298:9)
    at emitNone (events.js:72:20)
    at Socket.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:905:12)
    at nextTickCallbackWith2Args (node.js:474:9)
    at process._tickCallback (node.js:388:17)

**Comment by awlayton** [comment]
When you post stack traces, please be sure you have `BLUEBIRD_DEBUG=1`. Promises make them not that useful without that set.

**Comment by mato75** [comment]
This is the log that I get.

      Page Error { [HeadlessError: Request() error evaluating evaluate() call: Error: connect ECONNREFUSED 127.0.0.1:40862]
  name: 'HeadlessError',
  message: 'Request() error evaluating evaluate() call: Error: connect ECONNREFUSED 127.0.0.1:40862' }
14 Jan 18:12:33 - Expectention Success:  success  id:  5697e4ef5c982fb27f3d0806_56962dbf61c96dd7294733a0
14 Jan 18:12:33 - Log:  5697e4ef5c982fb27f3d0806
14 Jan 18:12:33 - Open Success:  success  id:  5697e4ef5c982fb27f3d07fd_56962dbf61c96dd7294733a0
Unhandled rejection HeadlessError: Phantom Process died
    at poll_func (/vagrant/node_modules/node-phantom-simple/node-phantom-simple.js:586:10)
    at /vagrant/node_modules/node-phantom-simple/node-phantom-simple.js:54:7
    at IncomingMessage.<anonymous> (/vagrant/node_modules/node-phantom-simple/node-phantom-simple.js:485:13)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:905:12)
    at nextTickCallbackWith2Args (node.js:474:9)
    at process._tickCallback (node.js:388:17)
From previous event:
    at Object.Officer._pageMaker (/vagrant/server/city/officer.js:108:16)
    at Object.Officer._setProps (/vagrant/server/city/officer.js:56:27)
    at Object.Officer (/vagrant/server/city/officer.js:17:10)
    at Object.Captain.order (/vagrant/server/city/captain.js:122:19)
    at Object.<anonymous> (/vagrant/server/city/mayor.js:119:48)

**Comment by mato75** [comment]
```
Unhandled rejection Error: page-evaluation-error
    at /vagrant/server/city/officer.js:183:21
From previous event:
    at /vagrant/server/city/officer.js:181:24
    at processImmediate [as _immediateCallback] (timers.js:383:17)
From previous event:
    at Object.Officer._ready (/vagrant/server/city/officer.js:180:19)
    at Object.Officer.evaluate (/vagrant/server/city/officer.js:854:21)
    at null._repeat (/vagrant/server/city/officer.js:1301:34)
    at wrapper [as _onTimeout] (timers.js:275:11)
    at Timer.listOnTimeout (timers.js:92:15)
```

**Comment by mato75** [comment]
Fixed, no more issue on error. Had to use resolve, because was getting a lot of Unhandled rejection Error from bluebird.

**Comment by awlayton** [comment]
Could you perhaps post some code showing how you fixed it? I am not sure what you mean.

**Comment by dineshsprabu** [comment]
Hi,

Currently I'm facing the same error. Can you help me fixing this?

I can understand that phantom is getting closed before the callback execute. But i'm facing the same error even if i remove the exit. Please help me fixing this.

Unhandled rejection HeadlessError: Phantom Process die

Unhandled rejection HeadlessError: Request() error evaluating createPage() call: Error: socket hang up

**Comment by ohenepee** [comment]
@mato75 could you please be more as to how you fixed the issue?

**Comment by shesmu** [comment]
@mato75  Also getting the same error, if you could let us know how you fixed it that would be appreciated.

**Comment by ohenepee** [comment]
This is the SOLUTION I ended up with since @mato75 went all silent on us

And YES my solution works if you're having the same PROBLEM I'm having, which is essentlally the FACT the node-horseman/phantomjs FAILS to open/launch/load-the-page|phantomjs-executable
