### ISSUE TITLE
Unhandled rejection HeadlessError: Request() error evaluating createPage() call

### ISSUE THREAD

**Issue by mato75** [johntitus/node-horseman#107]
We need to handle this error in a promise.

```javascript
Unhandled rejection HeadlessError: Request() error evaluating createPage() call: Error: socket hang up
at ClientRequest.<anonymous> (/vagrant/node_modules/node-phantom-simple/node-phantom-simple.js:504:18)
at emitOne (events.js:77:13)
at ClientRequest.emit (events.js:169:7)
at Socket.socketOnEnd (_http_client.js:298:9)
at emitNone (events.js:72:20)
at Socket.emit (events.js:166:7)
at endReadableNT (_stream_readable.js:905:12)
at nextTickCallbackWith2Args (node.js:474:9)
at process._tickCallback (node.js:388:17)
```

**Comment by awlayton** [comment]
It is being handed, you just don't have a `.catch` to catch it.

**Comment by mato75** [comment]
No I have a catch.

**Comment by awlayton** [comment]
Then could you get it to happen with `BLUEBIRD_DEBUG=1` set and post the stack trace?

**Comment by awlayton** [comment]
And post the code if possible.

**Comment by mato75** [comment]
Oh, sorry will do. Today I am working on something else, as soon as I have some time I will publish everything.

**Comment by mato75** [comment]
Unhandled rejection Error: page-evaluation-error
    at processImmediate [as _immediateCallback] (timers.js:383:17)

this is what I currently get.

**Comment by mato75** [comment]
```
Page Error [SyntaxError: Unexpected token E]
14 Jan 18:29:10 - Open Success:  page-evaluation-error  id:  5697e8abb53fe46d015d6ce4_56962dbf61c96dd72947339f
Unhandled rejection Error: page-evaluation-error
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

**Comment by mato75** [comment]
I do not know what is this:

             SyntaxError: Unexpected token E

No other information is passed, because when this is logged, testing doesnt work any more.

**Comment by awlayton** [comment]
I am pretty sure that message is coming from node-phantom-simple, but I cannot know without long stack traces on.
