### ISSUE TITLE
Request() error evaluating getProperty() 

### ISSUE THREAD

**Issue by Yashko** [johntitus/node-horseman#135]
Hello, i create 3 instances of horseman and it works fine, but after some time it calls this error:

HeadlessError: Request() error evaluating getProperty() call: Error: connect ECONNREFUSED

```
Unhandled rejection HeadlessError: Request() error evaluating getProperty() call: Error: connect ECONNREFUSED
    at ClientRequest.<anonymous> (/srv/node/node_modules/node-horseman/node_modules/node-phantom-simple/node-phantom-simple.js:506:18)
    at ClientRequest.emit (events.js:107:17)
    at Socket.socketErrorListener (_http_client.js:271:9)
    at Socket.emit (events.js:107:17)
    at net.js:459:14
    at process._tickCallback (node.js:355:11)
```

what can i do? how to catch this or fix?
thanks

**Comment by awlayton** [comment]
If possible, please run your thing with the environment variable `BLUEBIRD_DEBUG=1` set and post the stack trace that produces.

Also post some post some code or a description (ideally both) of what you are doing? What you have now is not much to go on.

**Comment by Yashko** [comment]
ye sure, but need to wait some time before my script output this error

about description:
simple web-crawler, now for 3 sites, for every site 1 horseman instance, and code like this:
`horseman[""+website.title]
				.cookies({"lang":"en"})
				.open("http://"+data[0])
				.waitForSelector(where)
				.text(where)
				.then(function(text) {
					console.log("got data: "+text);
					redis.set(data[0], text);
				});`

instance creating: 
`redis.smembers('sitesList', function(err, res) {
		async.eachSeries(res, function(item, nextItem) {
			horseman[""+item.title] = new Horseman({phantomPath: phantomjs.path});
			console.log("horseman instance created for "+data[0]);
			nextItem();
		}, function () {
			callback();
		});
	});		`

**Comment by Yashko** [comment]
here is error what i get now:
```
here is error what i get now:
```
Unhandled rejection HeadlessError: Phantom Process died
    at poll_func (/srv/node/node_modules/node-horseman/node_modules/node-phantom-simple/node-phantom-simple.js:584:10)
    at /srv/node/node_modules/node-horseman/node_modules/node-phantom-simple/node-phantom-simple.js:52:7
    at IncomingMessage.<anonymous> (/srv/node/node_modules/node-horseman/node_modules/node-phantom-simple/node-phantom-simple.js:493:11)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)
From previous event:
    at null.<anonymous> (/srv/node/node_modules/node-horseman/lib/actions.js:51:10)
From previous event:
    at exports.open (/srv/node/node_modules/node-horseman/lib/actions.js:50:20)
    at null.<anonymous> (/srv/node/node_modules/node-horseman/lib/index.js:166:22)
    at processImmediate [as _immediateCallback] (timers.js:367:17)
From previous event:
    at Promise.HorsemanPromise.(anonymous function) [as open] (/srv/node/node_modules/node-horseman/lib/index.js:164:15)
    at /srv/node/monitoring.js:43:6
    at /srv/node/node_modules/async/lib/async.js:181:20
    at iterate (/srv/node/node_modules/async/lib/async.js:262:13)
    at Object.async.forEachOfSeries.async.eachOfSeries (/srv/node/node_modules/async/lib/async.js:281:9)
    at Object.async.forEachSeries.async.eachSeries (/srv/node/node_modules/async/lib/async.js:214:22)
    at Command.callback (/srv/node/monitoring.js:32:9)
    at RedisClient.return_reply (/srv/node/node_modules/redis/index.js:664:25)
    at JavascriptReplyParser.reply_parser.send_reply (/srv/node/node_modules/redis/index.js:332:14)
    at JavascriptReplyParser.run (/srv/node/node_modules/redis/lib/parsers/javascript.js:132:18)
    at JavascriptReplyParser.execute (/srv/node/node_modules/redis/lib/parsers/javascript.js:107:10)
    at Socket.<anonymous> (/srv/node/node_modules/redis/index.js:131:27)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
    at TCP.onread (net.js:540:20)
```
```

**Comment by awlayton** [comment]
The error in the stack trace is a different one that you first posted. This one is the same as #111.

**Comment by Yashko** [comment]
in #111 

> Yeah @0x1mason, horseman does not always find PhantomJS when it is installed by the phantomjs npm module, as mentioned in #101.

but i have 
` horseman[""+item.title] = new Horseman({phantomPath: phantomjs.path}); `
so why i get this error?

**Comment by awlayton** [comment]
The opener of that issue never responded if that was the fix. Anyways, all I meant was it is the same error. I am not sure the cause is the same.

**Comment by Yashko** [comment]
anyway, how i can catch errors like this? so i can create new instances of horseman and my script doesnt stop work

**Comment by awlayton** [comment]
Unfortunately I am not sure. `HeadlessError` is coming from node-phantom-simple. I have not figured out why it sometimes kills everything.

**Comment by awlayton** [comment]
You could try adding a `.catch` to the end of the chain for each horseman and see if that catches the rejection.

**Comment by awlayton** [comment]
Closing this because there has been no activity, and all the changes in v3 could very well have fixed it.

**Comment by antonymca** [comment]
i am facing the above issue in my mac, it was running fine few months back. But now i am getting this error.

 name: 'HeadlessError',
  message: 'Request() error evaluating getProperty() call: Error: connect ECONNREFUSED ::1:64158' }
{ HeadlessError: Request() error evaluating getProperty() call: Error: connect ECONNREFUSED ::1:64157

Any help.
