### ISSUE TITLE
[Windows] Error: Cannot find module 'node-horseman'

### ISSUE THREAD

**Issue by M4rt1n17** [johntitus/node-horseman#137]
Hi, I'm using Windows Pro 10 x64 and and somehow could not install node-horseman correctly.
I installed it with: "npm install node-horseman"
But still getting this error:

```
module.js:341
    throw err;
    ^

Error: Cannot find module 'node-horseman'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (C:\Users\Looper\Desktop\Looper\visit.js:1:79)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
```

Node & npm:

```
C:\Windows\system32>npm -v
3.8.0

C:\Windows\system32>node -v
v5.7.1
```

Hope you can help me. Also everything is in the path. 

PATH (User): `C:\Ruby22-x64\bin;C:\Users\Looper\AppData\Roaming\npm;%appdata%\npm;C:\nodejs`

PATH (system): `C:\Python27\;C:\Python27\Scripts;C:\Perl64\site\bin;C:\Perl64\bin;%SystemRoot%\system32;%SystemRoot%;%SystemRoot%\System32\Wbem;%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\;%appdata%\npm\;C:\nodejs\;C:\phantomjs\bin\`

Best regards, Martin

**Comment by awlayton** [comment]
This error has nothing to do with horseman itself. For whatever reason, node just isn't finding horseman.

Make sure you installed it in the directory of your project, that's the only idea I have.
