### ISSUE TITLE
Not every website can be opened by horseman?

### ISSUE THREAD

**Issue by localhost5482436** [johntitus/node-horseman#138]
```js
var Horseman = require('node-horseman');
var horseman = new Horseman();

horseman
  .userAgent("Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.75 Safari/537.36")
  .open("http://www.lagou.com")    
  .do(function(done){
	  console.log("Hello,bky");
    setTimeout(done,1000);
  })
  .close();
```

open this url  has  error:
```
Unhandled rejection HeadlessError: Phantom Process died
    at ClientRequest.<anonymous> (/opt/node/crawler/node_modules/node-horseman/node_modules/node-phantom-simple/node-phantom-simple.js:659:12)
    at ClientRequest.emit (events.js:107:17)
    at Socket.socketErrorListener (_http_client.js:271:9)
    at Socket.emit (events.js:107:17)
    at net.js:459:14
    at process._tickCallback (node.js:355:11)

```
But  open http://www.baidu.com OR  http://www.cnblogs.com will be OK,

**Comment by johntitus** [comment]
This code works fine for me. The only output is `Hello,bky`. What operating system are you using, along with which version of Phantom JS & which version of node-horseman?

**Comment by localhost5482436** [comment]
```
 CentOS release 6.2

node-horseman@2.8.2

 phantomjs2@2.2.0
```

is it OK？

**Comment by johntitus** [comment]
The latest release of phantomjs is 2.1, I think?

**Comment by localhost5482436** [comment]
run command : npm list
```
├─┬ node-horseman@2.8.2
│ ├── bluebird@2.10.2
│ ├── clone@0.1.19
│ ├─┬ debug@2.2.0
│ │ └── ms@0.7.1
│ ├─┬ defaults@1.0.3
│ │ └── clone@1.0.2
│ └── node-phantom-simple@2.2.4
└─┬ phantomjs2@2.2.0
  ├── adm-zip@0.4.4
  ├─┬ fs-extra@0.23.1
  │ ├── graceful-fs@4.1.3
  │ ├── jsonfile@2.2.3
  │ ├── path-is-absolute@1.0.0
  │ └─┬ rimraf@2.5.2
  │   └─┬ glob@7.0.3
  │     ├─┬ inflight@1.0.4
  │     │ └── wrappy@1.0.1
  │     ├── inherits@2.0.1
  │     ├─┬ minimatch@3.0.0
  │     │ └─┬ brace-expansion@1.1.3
  │     │   ├── balanced-match@0.3.0
  │     │   └── concat-map@0.0.1
  │     └─┬ once@1.3.3
  │       └── wrappy@1.0.1
  ├─┬ glob@6.0.4
  │ ├─┬ inflight@1.0.4
  │ │ └── wrappy@1.0.1
  │ ├── inherits@2.0.1
  │ ├─┬ minimatch@3.0.0
  │ │ └─┬ brace-expansion@1.1.3
  │ │   ├── balanced-match@0.3.0
  │ │   └── concat-map@0.0.1
  │ ├─┬ once@1.3.3
  │ │ └── wrappy@1.0.1
  │ └── path-is-absolute@1.0.0
  ├── kew@0.4.0
  ├─┬ mkdirp@0.5.1
  │ └── minimist@0.0.8
  ├─┬ npmconf@2.1.1
  │ ├─┬ config-chain@1.1.10
  │ │ └── proto-list@1.2.4
  │ ├── inherits@2.0.1
  │ ├── ini@1.3.4
  │ ├─┬ nopt@3.0.6
  │ │ └── abbrev@1.0.7
  │ ├─┬ once@1.3.3
  │ │ └── wrappy@1.0.1
  │ ├─┬ osenv@0.1.3
  │ │ ├── os-homedir@1.0.1
  │ │ └── os-tmpdir@1.0.1
  │ ├── semver@4.3.6
  │ └── uid-number@0.0.5
  ├── progress@1.1.8
  ├─┬ request@2.42.0
  │ ├── aws-sign2@0.5.0
  │ ├─┬ bl@0.9.5
  │ │ └─┬ readable-stream@1.0.33
  │ │   ├── core-util-is@1.0.2
  │ │   ├── inherits@2.0.1
  │ │   ├── isarray@0.0.1
  │ │   └── string_decoder@0.10.31
  │ ├── caseless@0.6.0
  │ ├── forever-agent@0.5.2
  │ ├─┬ form-data@0.1.4
  │ │ ├── async@0.9.2
  │ │ ├─┬ combined-stream@0.0.7
  │ │ │ └── delayed-stream@0.0.5
  │ │ └── mime@1.2.11
  │ ├─┬ hawk@1.1.1
  │ │ ├── boom@0.4.2
  │ │ ├── cryptiles@0.2.2
  │ │ ├── hoek@0.9.1
  │ │ └── sntp@0.2.4
  │ ├─┬ http-signature@0.10.1
  │ │ ├── asn1@0.1.11
  │ │ ├── assert-plus@0.1.5
  │ │ └── ctype@0.5.3
  │ ├── json-stringify-safe@5.0.1
  │ ├── mime-types@1.0.2
  │ ├── node-uuid@1.4.7
  │ ├── oauth-sign@0.4.0
  │ ├── qs@1.2.2
  │ ├── stringstream@0.0.5
  │ ├── tough-cookie@2.2.1
  │ └── tunnel-agent@0.4.2
  ├─┬ request-progress@0.3.1
  │ └── throttleit@0.0.2
  └── which@1.0.9``
```
This is all information

**Comment by localhost5482436** [comment]
you are right 
                 the latest release of phantomjs is 2.1
I installed is phantomjs-2.1.1

**Comment by awlayton** [comment]
The posted code works for me as well. Could you run it again with the environment variable `BLUEBIRD_DEBUG=1` set?

**Comment by localhost5482436** [comment]
@awlayton 
```
Unhandled rejection HeadlessError: Phantom Process died
    at ClientRequest.<anonymous> (/opt/node/crawler/node_modules/node-horseman/node_modules/node-phantom-simple/node-phantom-simple.js:659:12)
    at ClientRequest.emit (events.js:107:17)
    at Socket.socketErrorListener (_http_client.js:271:9)
    at Socket.emit (events.js:107:17)
    at net.js:459:14
    at process._tickCallback (node.js:355:11)
From previous event:
    at null.<anonymous> (/opt/node/crawler/node_modules/node-horseman/lib/actions.js:51:10)
From previous event:
    at exports.open (/opt/node/crawler/node_modules/node-horseman/lib/actions.js:50:20)
    at null.<anonymous> (/opt/node/crawler/node_modules/node-horseman/lib/index.js:166:22)
    at processImmediate [as _immediateCallback] (timers.js:367:17)
From previous event:
    at Promise.HorsemanPromise.(anonymous function) [as open] (/opt/node/crawler/node_modules/node-horseman/lib/index.js:164:15)
    at Object.<anonymous> (/opt/node/crawler/horseman_demolg.js:8:4)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
 
```

I'm very curious why this Url not work for me,but the other is OK……

**Comment by awlayton** [comment]
Hm... It really is dying in the `.open` call. Just to be sure, are you able to open http://www.lagou.com on the same computer using something besides horseman?

**Comment by localhost5482436** [comment]
network is well,run 
```
 ping www.lagou.com     
PING opt.ecoma.ourwebpic.com (183.131.124.38) 56(84) bytes of data.
64 bytes from 183.131.124.38: icmp_seq=2 ttl=50 time=42.5 ms
64 bytes from 183.131.124.38: icmp_seq=3 ttl=50 time=42.5 ms
64 bytes from 183.131.124.38: icmp_seq=4 ttl=50 time=42.6 ms
64 bytes from 183.131.124.38: icmp_seq=5 ttl=50 time=42.3 ms
64 bytes from 183.131.124.38: icmp_seq=6 ttl=50 time=42.4 ms
```

and use  **phantomjs-node  ** can open it

**Comment by awlayton** [comment]
Weird. If you run it with `DEBUG='node-phantom-simple:*'`, do you get any more output?

**Comment by localhost5482436** [comment]
@awlayton  the output is same,   for this website I'm speechless, But To crawler this website is my destination.

**Comment by localhost5482436** [comment]
@awlayton    I sovled it , the reason is that my version is too lower ,I update to  v5,
 It's Run, Ahahah……
thank  you

**Comment by localhost5482436** [comment]
@awlayton 
V5 ------- nodejs version 5.0.0
Now it doesn't work again…… driver me crazy

**Comment by awlayton** [comment]
It works for me with Node.js versions 0.10.41, 0.12.12, 4.3.1, and 5.7.1 (i.e., all the version I have tried).

**Comment by awlayton** [comment]
Out of curiosity, have you tried v3 of horseman @localhost5482436? I am kind of out of ideas since this error only happens for you...

**Comment by localhost5482436** [comment]
@awlayton , Thank you for reminding，After Install V3 of horseman, It works for me now    :+1:

**Comment by awlayton** [comment]
I guess I'll close this since it is fixed in v3. I am still curious what the problem was though...
