### ISSUE TITLE
Unhandled rejection TimeoutError: timeout during .waitFor() after 5033ms

### ISSUE THREAD

**Issue by mort3za** [johntitus/node-horseman#160]
For every site I test, I see this error:
```
Unhandled rejection TimeoutError: timeout during .waitFor() after 5033 ms
    at waitForCheck (/home/morteza/www/crawler/node_modules/node-horseman/lib/actions.js:1623:13)
    at wrapper (timers.js:275:19)
    at Timer.listOnTimeout (timers.js:92:15)
```

This is the code:
```javascript
var Horseman = require('node-horseman');
var horseman = new Horseman({timeout: 5000});

horseman
  .userAgent('Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.73 Safari/537.36')
  .open('http://blog.ir')
  .waitForSelector('.sidedContent')
  .count('.sidedContent')
  .log() // prints out the number of results
  .close();
```
Also I tested with {timeout:20000}.

**Comment by awlayton** [comment]
It's because the selector you are waiting for never exists on the page, thus the waiting times out eventually. I think you wanted `'#sidedContent'`.

**Comment by mort3za** [comment]
Oh! What a stupid mistake. Thank you.
