### ISSUE TITLE
`Unhandled reject Error: Failed to load url`

### ISSUE THREAD

**Issue by winghouchan** [johntitus/node-horseman#188]
@minhchu has reported a bug they are facing where an `Unhandled rejection Error: Failed to load url` is thrown. This is similar to #180 however the case is not due to SlimerJS in which #180 is specifically for. This new issue will track the new case @minhchu is facing.

The test case which can reproduce the issue is below:

```javascript
var Horseman = require('node-horseman');
var horseman = new Horseman();

horseman
  .userAgent('Mozilla/5.0 (Windows NT 6.1; WOW64; rv:27.0) Gecko/20100101 Firefox/27.0')
  .open('https://www.google.com/search?site=&tbm=isch&source=hp&biw=1366&bih=640&q=moon')
  .screenshot('example.jpg')
  .close();
```

The output is below: 

```
  horseman using PhantomJS from $PATH +0ms
  horseman .setup() creating phantom instance on 12406 +4ms
  horseman phantom created +673ms
  horseman phantom version 2.1.1 +17ms
  horseman page created +11ms
  horseman phantomjs onLoadFinished triggered +13ms success NaN
  horseman injected jQuery +46ms
  horseman .userAgent() set +20ms Mozilla/5.0 (Windows NT 6.1; WOW64; rv:27.0) Gecko/20100101 Firefox/27.0
  horseman .open() +1ms https://www.google.com/search?site=&tbm=isch&source=hp&biw=1366&bih=640&q=moon
  horseman phantomjs onLoadFinished triggered +899ms success 1
  horseman phantomjs onLoadFinished triggered +103ms fail 2
  horseman injected jQuery +1ms
  horseman .close(). +4ms
Unhandled rejection Error: Failed to load url
    at checkStatus (/Users/user/Projects/node_modules/node-horseman/lib/index.js:276:16)
    at tryCatcher (/Users/user/Projects/node_modules/bluebird/js/release/util.js:16:23)
    at Function.Promise.attempt.Promise.try (/Users/user/Projects/node_modules/bluebird/js/release/method.js:39:29)
    at Object.loadFinishedSetup [as onLoadFinished] (/Users/user/Projects/node_modules/node-horseman/lib/index.js:274:43)
    at /Users/user/Projects/node_modules/node-phantom-simple/node-phantom-simple.js:636:30
    at Array.forEach (native)
    at IncomingMessage.<anonymous> (/Users/user/Projects/node_modules/node-phantom-simple/node-phantom-simple.js:617:17)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:913:12)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)
```

**Comment by winghouchan** [comment]
Duplicates #187 😵 which @minhchu was able to submit 40 seconds before this one.

**Comment by winghouchan** [comment]
It's interesting that the `onLoadFinished` event is triggered twice:

```
  horseman phantomjs onLoadFinished triggered +899ms success 1
  horseman phantomjs onLoadFinished triggered +103ms fail 2
```

One with `success` and the other with `fail`.

**Comment by winghouchan** [comment]
Test case above submitted by @minhchu does not reliably reproduce the issue. 😕

**Comment by winghouchan** [comment]
Another case where the `onLoadFinished` event was triggered more than once:

```
  horseman using PhantomJS from $PATH +0ms
  horseman .setup() creating phantom instance on 12406 +5ms
  horseman phantom created +492ms
  horseman phantom version 2.1.1 +19ms
  horseman page created +11ms
  horseman phantomjs onLoadFinished triggered +14ms success NaN
  horseman injected jQuery +28ms
  horseman .userAgent() set +19ms Mozilla/5.0 (Windows NT 6.1; WOW64; rv:27.0) Gecko/20100101 Firefox/27.0
  horseman .open() +1ms https://www.google.com/search?site=&tbm=isch&source=hp&biw=1366&bih=640&q=moon
  horseman phantomjs onLoadFinished triggered +904ms success 1
  horseman phantomjs onLoadFinished triggered +65ms fail 2
  horseman phantomjs onLoadFinished triggered +3ms success 3
  horseman injected jQuery +0ms
  horseman .close(). +5ms
  horseman jQuery not injected - already exists on page +10ms
Unhandled rejection Error: Failed to load url
    at checkStatus (/Users/user/Projects/node_modules/node-horseman/lib/index.js:276:16)
    at Object.loadFinishedSetup [as onLoadFinished] (/Users/user/Projects/node_modules/node-horseman/lib/index.js:274:43)
    at /Users/user/Projects/node_modules/node-phantom-simple/node-phantom-simple.js:636:30
    at Array.forEach (native)
    at IncomingMessage.<anonymous> (/Users/user/Projects/node_modules/node-phantom-simple/node-phantom-simple.js:617:17)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:913:12)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)
From previous event:
    at Object.page.loadedPromise (/Users/user/Projects/node_modules/node-horseman/lib/index.js:233:27)
    at Horseman.<anonymous> (/Users/user/Projects/node_modules/node-horseman/lib/actions.js:70:26)
From previous event:
    at Horseman.exports.open (/Users/user/Projects/node_modules/node-horseman/lib/actions.js:60:20)
    at Horseman.(anonymous function) [as open] (/Users/user/Projects/node_modules/node-horseman/lib/index.js:398:17)
    at Horseman.<anonymous> (/Users/user/Projects/node_modules/node-horseman/lib/index.js:406:22)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
From previous event:
    at Promise.HorsemanPromise.(anonymous function) [as open] (/Users/user/Projects/node_modules/node-horseman/lib/index.js:404:15)
    at Object.<anonymous> (/Users/user/Projects/foo.js:6:4)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3
```

**Comment by minhchu** [comment]
wow, haha :grin:

**Comment by awlayton** [comment]
This is an odd one. When I run the script it works fine and onLoadFInished is only triggered once after the open. What node version and operating system are you using?

**Comment by winghouchan** [comment]
My Node.js version is **v4.4.4** and my OS is **OS X El Capitan v10.11.4**.

**Comment by minhchu** [comment]
node -v **5.3.0**, npm -v **3.3.12**, Windows 7 64 bit.

**Comment by ianalexander** [comment]
For what it's worth: I'm having this issue as well but it is very indeterminate for me. I've been unable to reproduce it reliably. My code runs on a loop and I see this error pop up around 25% of the time. I've used this to help reproduce it:

```js
function main() {
  // ...horseman do stuff...
  horseman.finally(() => {
    console.log(`Waiting ${process.env.DELAY} minute(s)...`);
    setTimeout(main, process.env.DELAY*60*1000);
  });
}
```

Hope this helps, and for the record:
```sh
$ node --version
v6.2.2
$ npm --version
3.9.5
$ npm list node-horseman
...
└── node-horseman@3.0.1 
```

**Comment by bmills22** [comment]
I also have this issue. For me it happens more times than it works. After a click() and waitForPage(), it throws the failed url error.

```
node: v5.6.0
horseman: node-horseman@3.1.1
OS: Ubuntu 14.04LTS
```

**Comment by abagh0703** [comment]
I'm having this issue too: .value --> .click --> .waitForNextPage() --> "Failed to load url"

    node: v4.2.3
    npm: v3.10.3
    horseman: v3.1.1
    OS: Windows 10 64 bit

**Comment by sayanriju** [comment]
Same issue here. Works intermittently, but mostly it doesn't. Makes horseman unusable for /me. 😢

**Comment by awlayton** [comment]
Why can't you just catch the rejection @sayanriju? I have still been unable to reproduce this.

**Comment by OrtoNormale** [comment]
Me too have this problem. It happens randomly.
I'm trying to login several user to a page using these statements:

```
var horseman = new Horseman(Global.horsemanOptions);
usersList.forEach(function(user){        
    horseman
               // Open the page
               .open(WEB_PAGE)
               .value('#loginform > input[name=username]', user.username)
               .value('#loginform > input[name=password]', user.password)
               .click('#loginform > button[type=submit]')
               .waitForNextPage()
               .screenshot(user.username + '.png')
               .then(function(){
                   console.log(user.username + ' LOGGED IN')
               })
               .....
               .....

});
```

Error seems to be raised for the sequence:
```
.click('#loginform > button[type=submit]')
.waitForNextPage()
```
because commenting those statements, error is not raised (but others yes).

The strange thing is that screenshots are taken correctly, they are images of a  successfully login. But next statements are not correctly executed.

I'm running it in **Arch Linux**  and **nodejs v6.3.1**

Does anybody know a solution for that?

**Comment by johntitus** [comment]
@OrtoNormale I don't think this is related to the bug you're seeing, but - you're trying to use horseman, which is asynchronous, in a synchronous loop. Each .action() takes time, but by the time the first page is open, your loop has probably completed.

**Comment by OrtoNormale** [comment]
There was an error in my code snippet. At every iteration a new horseman object is initialized. The statement with new Horseman() has to be moved inside the loop. So every user has its own instance. But is'nt .open() waiting for page load before go on?

**Comment by johntitus** [comment]
Yes, but by the time the first user's page is open, the loop has likely completed, and the `user` variable will be the last user in the list.  Horseman doesn't block the loop. You could move the horseman stuff inside a function, and then just send the user to the function. That should fix your scope issue.

```js
function doStuff(user){
  var horseman = new Horseman(Global.horsemanOptions);
  horseman
               // Open the page
               .open(WEB_PAGE)
               .value('#loginform > input[name=username]', user.username)
               .value('#loginform > input[name=password]', user.password)
               .click('#loginform > button[type=submit]')
               .waitForNextPage()
               .screenshot(user.username + '.png')
               .then(function(){
                   console.log(user.username + ' LOGGED IN')
               })
}
usersList.forEach(doStuff);
```

**Comment by OrtoNormale** [comment]
Thanks for the answer. As soon as possible I'll try and report.

**Comment by OrtoNormale** [comment]
Unfortunately problem persits. Here the code I tried:

```
var performLoginTask = function(usersList){

    var task = function(user){
        var horseman = new Horseman(Global.horsemanOptions);
        horseman
            .on('consoleMessage', function( msg ){
                console.log(msg);
            })
            // Open page
            .open(WEB_PAGE)
            .value('#loginform > input[name=username]', user.username)
            .value('#loginform > input[name=password]', user.password)
            .click('#loginform > button[type=submit]')
            .waitForNextPage()
            .....
            .....
            .....
    };

    usersList.forEach(task);
    
            
};

performLoginTask(usersList);
```

anyway it seems very similar to my version.

Error is the following:

`Unhandled rejection Error: Failed to load url`

 It's a really powerful tool and It is a shame not use this tool due to this problem.

**Comment by johntitus** [comment]
at the bottom of your horseman chain, can you add a .catch()?

**Comment by OrtoNormale** [comment]
Added catch, but errors still throwed:

 var performLoginTask = function(usersList){

     var task = function(user){
         var horseman = new Horseman(Global.horsemanOptions);
         horseman
             .on('consoleMessage', function( msg ){
                 console.log(msg);
             })
             // Open page
             .open(WEB_PAGE)
             .value('#loginform > input[name=username]', user.username)
             .value('#loginform > input[name=password]', user.password)
             .click('#loginform > button[type=submit]')
             .waitForNextPage()
             .....
             .....
             .....
             .catch(function(error){console.log(error)})
     };

     usersList.forEach(task);


 };

and console.log() in block catch print the same as throwed error.

**Comment by OrtoNormale** [comment]
Could the problem be related to a redirect (HTTP code 302) that is done after login?

**Comment by johntitus** [comment]
If it's being caught in the `catch`, can you just ignore it? Does it get
thrown for every `user`, or just for one or two?

**Comment by OrtoNormale** [comment]
The error is thrown only for one or two and randomly, not always the same users.

Ok, I'll try to handle that error in catch().

**Comment by johntitus** [comment]
How many users are you trying to do at the same time? I wonder if it's
blowing up Phantom because of memory issues...

**Comment by OrtoNormale** [comment]
At the moment max 10 users, in future maybe more.
However It happens even using only 1 user sometimes.
For now I'm handling it in catch() block by recalling the task.
Not the best solution, but it works.

**Comment by shockey** [comment]
Echoing what's been said in the earlier comments.

Horseman appears to hang after this happens.

My output, from the `.catch(err => console.log(err.stack || err))` I added:

```
  horseman .keyboardEvent() +3ms keypress w null
  horseman .keyboardEvent() +4ms keypress X null
  horseman .keyboardEvent() +4ms keypress 8 null
  horseman .click() +0ms #sign-in-button
  horseman .click() done +22ms
  horseman .open() +1ms [redacted]
  horseman phantomjs onLoadFinished triggered +4ms fail 2
  horseman phantomjs onLoadFinished triggered +2ms fail 3
Error: Failed to GET url: [redacted]
    at checkStatus ([cwd]/node_modules/node-horseman/lib/actions.js:78:16)
    at [cwd]/node_modules/node-phantom-simple/node-phantom-simple.js:60:18
    at IncomingMessage.<anonymous> ([cwd]/node_modules/node-phantom-simple/node-phantom-simple.js:645:9)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:903:12)
    at doNTCallback2 (node.js:439:9)
    at process._tickCallback (node.js:353:17)
From previous event:
    at Horseman.<anonymous> ([cwd]/node_modules/node-horseman/lib/actions.js:76:5)
From previous event:
    at Horseman.exports.open ([cwd]/node_modules/node-horseman/lib/actions.js:60:20)
    at Horseman.(anonymous function) [as open] ([cwd]/node_modules/node-horseman/lib/index.js:402:17)
    at Horseman.<anonymous> ([cwd]/node_modules/node-horseman/lib/index.js:410:22)
From previous event:
    at Promise.HorsemanPromise.(anonymous function) [as open] ([cwd]/node_modules/node-horseman/lib/index.js:408:15)
    at mainRoutine (app.js:30:6)
From previous event:
    at app.js:24:6
    at processImmediate [as _immediateCallback] (timers.js:368:17)
  horseman phantomjs onLoadFinished triggered +8s success 4
```

**Comment by shockey** [comment]
Worth noting: I, like @OrtoNormale, am `.open()`ing a page that may be responding with a `302 Found`.

**Comment by OrtoNormale** [comment]
As @shockey says, also in my case horseman jump directly in catch(){...} after that error is thrown and doesn't execute the rest of the code

**Comment by johntitus** [comment]
Can anyone provide a full test script to reproduce this? There are a ton of open PhantomJS issues [related to 302 redirects](https://github.com/ariya/phantomjs/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20302), but it's hard to pin down without a test script.

**Comment by OrtoNormale** [comment]
So what causing the issue is phantomJS? 

The site I'm testing isn't public (ready for production), so I cannot provide you link and scripts. But I think that any site with redirect could throw that error.

**Comment by shockey** [comment]
I'm in the same boat- the project that has this issue is contract work for a client.

I'll try to put something together that fails in the same way.

**Comment by sohilv** [comment]
For me it was SSL Handshake was causing error, i get it figure out using following event handler.

For same i used ignoreSSLErrors: true while creating horseman object, it resolves the issue.

`    
horseman.on('resourceError',function(err)  {
        console.log(err);
      });

`

**Comment by shockey** [comment]
That didn't fix it for me, but tuning into `resourceError`s did give me a new piece of info:

```
{ 
  errorCode: 5,
  errorString: 'Operation canceled',
  id: 20,
  status: 200,
  statusText: 'OK',
  url: [redacted]
}
```

**Comment by sohilv** [comment]
@shockey Seems wherever you are hosting site, https connection is being drop. Just for debug, try running you code outside of firewall if any , see what result it gives.

**Comment by johntitus** [comment]
Can everyone running into this issue try setting their horseman timeout to something big, like 30 seconds, and retrying?

**Comment by MegaThorx** [comment]
The `Error: Failed to load url` gets thrown when i use the .close() method. Idk why? And i still can't really catch the error.

**Comment by design2dev** [comment]
We are getting this too. What's the ETA on the fix?

**Comment by awlayton** [comment]
There is no ETA @design2dev, we still have no way to reproduce and be sure there even *is* a bug. Sometimes PhantomJS can *legitimately* fail to load a URL for some reason.

**Comment by overflowz** [comment]
I get it too. 
````
horseman .open() +2ms [url edited]                                                                          
  horseman phantomjs onLoadFinished triggered +236ms fail 3                                                                                                                             
  horseman phantomjs onLoadFinished triggered +2ms success 4 
Error: Failed to GET url: [url edited]  
````

But instead of loop, it throws up randomly (re-run application). Also, why onLoadFinished is being triggered twice?

**Comment by jharrowmortelliti** [comment]
Failed to GET url error is happening to me when I do 
`horseman.open('www.google.com')`
and not when I do
`horseman.open('http://www.google.com')`

**Comment by awlayton** [comment]
You have to [include the protocol](http://phantomjs.org/quick-start.html#page-loading) @jharrowmortelliti. If you don't give one, I think PhantomJS tries `file:`, but I am not positive.

**Comment by jharrowmortelliti** [comment]
I try to run the example at node-horseman/examples/links.js and it gives me the 'Failed to get url' error.

**Comment by awlayton** [comment]
Strange @jharrowmortelliti. When I run that example I get an error because the click selector no longer works, but once I change the selector to `"input[value='Google Search']"` it works fine.

**Comment by himanshu1691** [comment]
Any workaround for this issue?
I am facing this issue because a page is getting redirected.

**Comment by berstend** [comment]
I encountered the same issue, in my case adding a `.wait(3000)` before `.click` helped.

**Comment by balazs4** [comment]
Adding ``.wait(...)`` into the chain has also worked for me as workaround.

**Comment by GomuGomuMan** [comment]
I also get this issue. `.wait(randomInt)` seems to be a workaround solution.

**Comment by webdev** [comment]
What if there is no clicking in the function?

All I'm doing is opening a page, and scraping content, but pretty regularly getting `Unhandled rejection Error: Failed to load url`

**Comment by awlayton** [comment]
The error means what it says @webdev, PhantomJS failed to load a URL for some reason. This can be caused by a variety of things.

**Comment by Skyerin** [comment]
I've been experiencing this issue recently as well, whilst making an acceptance testing framework for my workplace. I did some digging into the issue using phantomjs directly, and it looks like phantomjs, during redirects from the page itself, cancels requests, and this is what causes the fail, even if the page loads successfully.

For context, in the application, when loading, the application will refresh. This is a legacy issue with it that currently won't change for a while. Doesn't cause any issues elsewhere though. Just with phantomjs

test case;
```
horseman
.viewport(1920, 1080)
.open(url)
.wait(5000)
.catch((error) => console.log(error))
.screenshot('./test.jpg')
.close();
```

DEBUG=horseman output (url obscured);

```
[jenkins@buildBox testing_framework]$ DEBUG=horseman node horseman_test.js
  horseman using PhantomJS from phantomjs-prebuilt module +0ms
  horseman .setup() creating phantom instance 1 +4ms
  horseman phantom created +127ms
  horseman phantom version 2.1.1 +16ms
  horseman page created +7ms
  horseman phantomjs onLoadFinished triggered success NaN +7ms
  horseman injected jQuery +16ms
  horseman .on() urlChanged set. +2ms
  horseman .viewport() set 1920 1080 +1ms
  horseman .open() http://url-of-application.com?action=new&username=testuser +4ms
  horseman phantomjs onLoadFinished triggered fail 1 +522ms
Error: Failed to GET url: http://url-of-application.com?action=new&username=testuser
    at checkStatus (/var/lib/jenkins/workspace/testing_framework/node_modules/node-horseman/lib/actions.js:78:16)
    at PassThroughHandlerContext.finallyHandler (/var/lib/jenkins/workspace/testing_framework/node_modules/bluebird/js/release/finally.js:57:23)
    at PassThroughHandlerContext.tryCatcher (/var/lib/jenkins/workspace/testing_framework/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/var/lib/jenkins/workspace/testing_framework/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/var/lib/jenkins/workspace/testing_framework/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/var/lib/jenkins/workspace/testing_framework/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/var/lib/jenkins/workspace/testing_framework/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/var/lib/jenkins/workspace/testing_framework/node_modules/bluebird/js/release/promise.js:638:18)
    at /var/lib/jenkins/workspace/testing_framework/node_modules/bluebird/js/release/nodeback.js:42:21
    at /var/lib/jenkins/workspace/testing_framework/node_modules/node-phantom-simple/node-phantom-simple.js:60:18
    at IncomingMessage.<anonymous> (/var/lib/jenkins/workspace/testing_framework/node_modules/node-phantom-simple/node-phantom-simple.js:645:9)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
  horseman .close(). +5ms
```

Adding output for the network requests received, we can see the following;

```
{ contentType: 'image/png',
  headers:
   [ { name: 'Date', value: 'Fri, 28 Apr 2017 10:00:09 GMT' },
     { name: 'Server', value: 'Apache/2.4.7 (Ubuntu)' },
     { name: 'Last-Modified',
       value: 'Mon, 10 Apr 2017 09:13:13 GMT' },
     { name: 'Accept-Ranges', value: 'bytes' },
     { name: 'Content-Length', value: '6531' },
     { name: 'Keep-Alive', value: 'timeout=5, max=100' },
     { name: 'Connection', value: 'Keep-Alive' },
     { name: 'Content-Type', value: 'image/png' } ],
  id: 11,
  redirectURL: null,
  stage: 'end',
  status: 200,
  statusText: 'OK',
  time: '2017-04-28T10:00:10.237Z',
  url: 'http://static.resources-url.com/application/images/app-ui/splash/splash_screen.png' }
{ contentType: null,
  headers: [],
  id: 15,
  redirectURL: null,
  stage: 'end',
  status: null,
  statusText: null,
  time: '2017-04-28T10:00:10.239Z',
  url: 'http://fonts.gstatic.com/s/ubuntu/v9/0ihfXUL2emPh0ROJezvraKCWcynf_cDxXwCLxiixG1c.ttf' }
```
From phantom and horseman, we can access the ttf file above; it is just the network requests being cancelled because of the redirect.

Looking at the phantomjs issues, I found https://github.com/ariya/phantomjs/issues/12750 which seems to be the same as the above here. It seems to specify that the issue is fixed in the 2.5 beta (which I haven't been able to test with unfortunately) but the issue doesn't feel to be in horseman for this.

**Comment by dhilditch** [comment]
The following fixed my issue:

QT_QPA_PLATFORM=offscreen 

Set that environment variable and the PhantomJS starts working again as does Horseman. As found here: https://github.com/ariya/phantomjs/issues/14376

**Comment by Skyerin** [comment]
@dhilditch that unfortunately didn't work for me. I had the same issue as @robertpallas did :(

@robertpallas - on your environments, could you test it with the phantom 2.5 beta? you can provide the path to node-horseman; just see if that solves the issue at all for you (as it is stated in https://github.com/ariya/phantomjs/issues/12750) ? Worth a shot at the very least... I didn't manage to get the beta working on both osx and centos, but you might have better luck than me.

**Comment by robertpallas** [comment]
### Issue
My issue is most probably related to one of the redirects being 0B HTTP 307 Internal Redirect from http to https. "Operation canceled" resourceError also comes as mentioned earlier in this thread. Recreation with HTTP only traffic with same HTTP redirects failed - Horseman works as expected.

### Phantom 2.5
I was able to run Phantom 2.5 within Docker with Ubuntu 16.04 under it and also set ENV variable `QT_QPA_PLATFORM=offscreen` but with or without it the app fails on earlier HTTP 302 redirect on same site with "Failed to load url" so it actually took me back a few steps.

### Next
Maybe I can somehow force the redirect to go directly to https and skip that Internal Redirect step? Any other workaround ideas are welcome.

**Comment by Skyerin** [comment]
@robertpallas I can't think of anything else you could try apart from modifying how your redirects are happening as they're happening from the page itself; unless we could add a delay somewhere somehow?

One of the ideas I was going to look at (because I deal with a SPA) was to modify the reload code so that when it comes from phantom (based off a flag/specific user agent) so that it would either add a delay to the reload (allowing network requests to finish first), or stop the reload altogether and I would do that manually in my tests.

The only other thing I could think of was just changing away from phantom and experimenting with chrome headless - although that is in a very barebones state and I do absolutely love how horseman makes things simple and lets itself be easily extensible.

**Comment by sashberd** [comment]
I have also this issue.
Here my data from log:

>  {errorCode: 5,
>   errorString: 'Operation canceled',
>   id: 30,
>   url: 'https://fecdn.user1st.info/CommFrame/Activation?ver=0.1.5.3#[my url]' }

my code is: 
```
 horseman.on('resourceError', function(err) {
            console.log(err);
        });
        horseman.viewport(20000, 100000)
            .open(horseManURL)
            .scrollTo(100000, 2000)
            .url()
            .then(function(currentURL) { location =currentURL }) 
            .evaluate(function(selector) {           

                return {
                    html: $(selector).html()
                }
            }, 'html')
            .then(function(data) {              
                data.location = location;           
                horseman.close();
                waterfallCallback(null, data);
            })
            .catch(function(data) {  
                horseman.close();
                return waterfallCallback(true);
            })
```
Any ideas for workarounds?

**Comment by sharifzadesina** [comment]
Same! I think we have to try to handle this error, then we can reload the page.

**Comment by hoangtrongphuc** [comment]
I have a work around solution: 
Modify index.js file in lib folder: 
Comment code from 291 to 294 line
			`return self.ready = HorsemanPromise.try(function checkStatus() {
				//if (status !== 'success') {
					//var err = new Error('Failed to load url');
					//return HorsemanPromise.reject(err);
				//}
			})`

**Comment by geek-caroline** [comment]
I found that these steps fixed this issue for me:

- deleting node_modules
- setting my node version to 8
- `npm install phantomjs`
- `npm install node-horseman`

I had previously had this issue repeatedly for any url that was complex (e.g. `http://via.placeholder.com/350x150` worked fine, but the example with `www.google.com` didn't)

I'm not sure if it was something to do with the order in which I installed things?  the fact that I'd installed node-horseman before phantom previously?  Or that I'd previously installed packages that I was no longer using (e.g. `horseman`)

Anyway, that's how I fixed my world.

**Comment by felipemullen** [comment]
@geek-caroline 
This happens to me if I do not specify the protocol, i.e. `www.google.com` will not work, but `http://www.google.com` works just fine

**Comment by kahirul** [comment]
Hi, I also experienced this. And I fixed this by changing my DNS to 8.8.8.8.

It seems very similar with issue at docker for mac https://github.com/docker/for-mac/issues/1317

**Comment by geek-caroline** [comment]
@felipemullen you may well be right, I've not seen the problem again and I've used the fully qualified `https://` address.  Perhaps that is the solution for most?

**Comment by chiefsmurph** [comment]
DNS set to 8.8.8.8, full https:// url, ignoreSSL: true, wait calls left and right ... getting this error fairly frequently.
