### ISSUE TITLE
Unhandled rejection Error: spawn phantomjs ENOENT

### ISSUE THREAD

**Issue by zeta-o** [johntitus/node-horseman#203]
When I try to run the example about google.com

Unhandled rejection Error: spawn phantomjs ENOENT
    at exports._errnoException (util.js:874:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:439:9)
    at process._tickCallback (node.js:353:17)
    at Function.Module.runMain (module.js:469:11)
    at startup (node.js:134:18)
    at node.js:961:3

**Comment by zeta-o** [comment]
My mistake guys! I had no installed phantom.

**Comment by malayladu** [comment]
I am getting following error. 

Unhandled rejection Error: spawn phantomjs ENOENT
    at exports._errnoException (util.js:907:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)
    at Function.Module.runMain (module.js:443:11)
    at startup (node.js:139:18)
    at node.js:974:3

**Comment by malayladu** [comment]
I got the issue. phantomjs was installed in node-modules/phantom/node-modules/.bin/phantomjs path. Created a symlink in /usr/local/bin/phantojs path and it worked.

**Comment by denysonique** [comment]
@malayladu Normally you shouldn't worry about having phantom in your PATH if you have phantomjs provided by one of the supported modules i.e. `phantomjs` or `phantomjs-prebuilt`. However I experienced the same issue with `phantomjs`, with `phantomjs-prebuilt` it works fine.

This is due to incompatibility between `phantomjs` and `node-phantom-simple` which `node-horseman` relies on.

In my spare time I am going to look into this and submit a patch.

**Comment by malayladu** [comment]
@denysonique Thanks for the clarification.

Looking forward to the patch :)

**Comment by neodev2** [comment]
I solved doing: `npm install phantomjs`

**Comment by walmartbaggg** [comment]
> I solved doing: `npm install phantomjs`

npm ERR! code 1
npm ERR! path /home/pi/SwordbattleBot/node_modules/phantomjs
npm ERR! command failed
npm ERR! command sh -c node install.js
npm ERR! PhantomJS not found on PATH
npm ERR! Unexpected platform or architecture: linux/arm
npm ERR! It seems there is no binary available for your platform/architecture
npm ERR! Try to install PhantomJS globally

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/trynaspyonmeehhhh/.npm/_logs/2022-07-04T01_13_24_272Z-debug-0.log
