### ISSUE TITLE
PhantomJS error when evaluate

### ISSUE THREAD

**Issue by vyatsun** [johntitus/node-horseman#223]
I've created a script to check network coverage for Vodafone.

``` javascript
var Horseman = require('node-horseman');

var postcode = "DE22 1GB";

var horseman = new Horseman({
            timeout: 10000
        });
horseman
            .viewport(1366, 768)
            .open('https://www.vodafone.co.uk/explore/network/uk-coverage-map/index.htm')
            .waitForSelector('iframe:nth-child(1)')
            .switchToFrame(0)
            .waitForSelector('#searchValue')
            .type('#searchValue', postcode)
            .click('#btnShowCoverage')
            .waitFor(function() {
                return $('#Pnl2GExpectContent').is(':visible');
            }, true)
            .wait(500)
            .click('#InternetEmainTab')
            .waitFor(function() {
                return $('#InternetandEmailDiv').is(':visible');
            }, true)
            .wait(700)
            .click('#LTETab')
            .waitFor(function() {
                return $('#LTEDiv').is(':visible');
            }, true)
            .wait(1000)
            .evaluate(function() {
                var b2G = document.querySelector('#report2G b');
                var b3G = document.querySelector('#report3G b');
                var bLTE = document.querySelector('#reportLTE b');
                var result;

                try {
                    result = {
                        '2G': b2G.innerHTML + b2G.nextSibling.nodeValue,
                        '3G': b3G.innerHTML + b3G.nextSibling.nodeValue,
                        '4G': bLTE.innerHTML + bLTE.nextSibling.nodeValue
                    };
                }
                catch (e) {
                    result = {
                        '2G': document.querySelector('#report2G').innerText,
                        '3G': document.querySelector('#report3G').innerText,
                        '4G': document.querySelector('#reportLTE').innerText
                    };
                }

                return result;
            })
             .then(function(result) {
                console.log('Vodafone results:');
                console.log(result);
                horseman.close();
            })
            .catch(function(err) {
                console.log("Vodafone error: ", err);
            });
```

It works fine most of the time, but 1 of 10 times I get the following error:

```
...
 horseman .click() +700ms #LTETab
  horseman .click() done +114ms
  horseman .waitFor() +0ms <anonymous>
  horseman:verbose .waitFor() iteration +55ms <anonymous> true 50 12406
  horseman .waitFor() completed successfully +0ms
  horseman .wait() +0ms 1000
  horseman .evaluate() +1s <anonymous>
  horseman:verbose onError +8ms ReferenceError: Can't find variable: __horseman
        undefined: 2 in evaluate
        : 74 in <anonymous> 12406
  horseman:verbose .evaluate() waiting for callback +0ms <anonymous> null 12406
  horseman .waitFor() +0ms waitForCb
Vodafone error:  { line: 2,
  popStackFrame: 
   { callBaseMethod: 
      { callBaseMethod: null,
        getBaseMethod: [Object],
        getBaseType: null,
        getInterfaces: null,
        getName: null,
        implementsInterface: null,
        inheritsFrom: null,
        initializeBase: null,
        isImplementedBy: null,
        isInstanceOfType: null,
        registerClass: null,
        registerEnum: null,
        registerInterface: null,
        resolveInheritance: null },
     getBaseMethod: null,
     getBaseType: null,
     getInterfaces: null,
     getName: null,
     implementsInterface: null,
     inheritsFrom: null,
     initializeBase: null,
     isImplementedBy: null,
     isInstanceOfType: null,
     registerClass: null,
     registerEnum: null,
     registerInterface: null,
     resolveInheritance: null },
  stack: 'waitForCb\nevaluatePage\n\nglobal code\nevaluateJavaScript@[native code]\nevaluate@phantomjs://platform/webpage.js:390:39\nphantomjs://code/bridge.js:121:61\n    at /home/ubuntu/workspace/node_modules/node-horseman/lib/actions.js:989:36\n    at tryCatcher (/home/ubuntu/workspace/node_modules/node-horseman/node_modules/bluebird/js/release/util.js:16:23)\n    at Function.Promise.fromNode.Promise.fromCallback (/home/ubuntu/workspace/node_modules/node-horseman/node_modules/bluebird/js/release/promise.js:176:30)\n    at Horseman.<anonymous> (/home/ubuntu/workspace/node_modules/node-horseman/lib/actions.js:987:29)\n    at Horseman.tryCatcher (/home/ubuntu/workspace/node_modules/node-horseman/node_modules/bluebird/js/release/util.js:16:23)\n    at Promise._settlePromiseFromHandler (/home/ubuntu/workspace/node_modules/node-horseman/node_modules/bluebird/js/release/promise.js:502:31)\n    at Promise._settlePromise (/home/ubuntu/workspace/node_modules/node-horseman/node_modules/bluebird/js/release/promise.js:559:18)\n    at Promise._settlePromiseCtx (/home/ubuntu/workspace/node_modules/node-horseman/node_modules/bluebird/js/release/promise.js:596:10)\n    at Async._drainQueue (/home/ubuntu/workspace/node_modules/node-horseman/node_modules/bluebird/js/release/async.js:143:12)\n    at Async._drainQueues (/home/ubuntu/workspace/node_modules/node-horseman/node_modules/bluebird/js/release/async.js:148:10)\n    at Immediate.Async.drainQueues [as _onImmediate] (/home/ubuntu/workspace/node_modules/node-horseman/node_modules/bluebird/js/release/async.js:17:14)\n    at processImmediate [as _immediateCallback] (timers.js:383:17)' }
  horseman phantomjs onLoadFinished triggered +813ms success 2
  horseman jQuery not injected - already exists on page +8ms
```

What can be the reason for that error?

**Comment by awlayton** [comment]
Closing because this should be resolved by #208.
