### ISSUE TITLE
Error with a dependencie of horseman

### ISSUE THREAD

**Issue by fernandoguedes** [johntitus/node-horseman#24]
Hello, I can't run a test using horseman, the apparent cause is a error of dependency of npm packets, follow:

/home/fguedes/projetos/tripper/node_modules/horseman/node_modules/jsdom/lib/jsdom.js:3
`jsdom 4.x onward only works on io.js, not Node.js™: https://github.com/tmpvar
^
SyntaxError: Unexpected token ILLEGAL
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/fguedes/projetos/tripper/node_modules/horseman/lib/horseman.js:3:13)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

Sorry but I can't find solution for this bug.

Any suggestions?

**Comment by johntitus** [comment]
Horseman doesn't depend on jsdom. Can you delete your `node_modules` directory and try an `npm install`?

**Comment by johntitus** [comment]
Closing due to lack of info.
