### ISSUE TITLE
String includes method seems to lead to error

### ISSUE THREAD

**Issue by karan1149** [johntitus/node-horseman#247]
Using the str.includes(str) method results in the following error every time: 

```
Unhandled rejection fn
evaluate

global code
evaluateJavaScript@[native code]
evaluate@phantomjs://platform/webpage.js:390:39
phantomjs://code/bridge.js:121:61    at Horseman.<anonymous> (/Users/Karan/Projects/bloomberg-law-scraper/node_modules/node-horseman/lib/actions.js:839:38)
    at Horseman.tryCatcher (/Users/Karan/Projects/bloomberg-law-scraper/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/Karan/Projects/bloomberg-law-scraper/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/Users/Karan/Projects/bloomberg-law-scraper/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromiseCtx (/Users/Karan/Projects/bloomberg-law-scraper/node_modules/bluebird/js/release/promise.js:604:10)
    at Async._drainQueue (/Users/Karan/Projects/bloomberg-law-scraper/node_modules/bluebird/js/release/async.js:143:12)
    at Async._drainQueues (/Users/Karan/Projects/bloomberg-law-scraper/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues (/Users/Karan/Projects/bloomberg-law-scraper/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:574:20)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback] (timers.js:533:5)
```

When I use indexOf != -1 to achieve the same effect, this works.

**Comment by awlayton** [comment]
This is because PhantomJS is missing some JavaScript functions other browsers have, such as `String.includes`. You can either load a polyfill into the browser (see #230), or just avoid the missing functions.
