### ISSUE TITLE
Unhanded rejection click on links.js example

### ISSUE THREAD

**Issue by pt-mpb** [johntitus/node-horseman#253]
Hi,

I need help. I'm trying to run the links.js example and I cannot get it to run. I'm getting the following error:

`horseman using PhantomJS from $PATH +0ms
  horseman .setup() creating phantom instance 1 +15ms
  horseman phantom created +534ms
  horseman phantom version 2.1.1 +17ms
  horseman page created +10ms
  horseman phantomjs onLoadFinished triggered success NaN +16ms
  horseman injected jQuery +35ms
  horseman .userAgent() set Mozilla/5.0 (Windows NT 6.1; WOW64; rv:27.0) Gecko/20100101 Firefox/27.0 +25ms
  horseman .open() http://www.google.com +1ms
  horseman phantomjs onLoadFinished triggered success 1 +2s
  horseman injected jQuery +15ms
  horseman .type() input[name='q'] horseman undefined +5ms
  horseman .keyboardEvent() keypress h null +32ms
  horseman .keyboardEvent() keypress o null +14ms
  horseman .keyboardEvent() keypress r null +9ms
  horseman .keyboardEvent() keypress s null +6ms
  horseman .keyboardEvent() keypress e null +5ms
  horseman .keyboardEvent() keypress m null +10ms
  horseman .keyboardEvent() keypress a null +9ms
  horseman .keyboardEvent() keypress n null +12ms
  horseman .click() button:contains('Google Search') +2ms
0
  horseman .close(). +13ms
Unhandled rejection click
evaluatePage

global code
evaluateJavaScript@[native code]
evaluate@phantomjs://platform/webpage.js:390:39
phantomjs://code/bridge.js:121:61
    at /Users/mariobessa/Development/temp/horseman_test/node_modules/node-horseman/lib/actions.js:989:36
    at tryCatcher (/Users/mariobessa/Development/temp/horseman_test/node_modules/bluebird/js/release/util.js:16:23)
    at Function.Promise.fromNode.Promise.fromCallback (/Users/mariobessa/Development/temp/horseman_test/node_modules/bluebird/js/release/promise.js:179:30)
    at Horseman.<anonymous> (/Users/mariobessa/Development/temp/horseman_test/node_modules/node-horseman/lib/actions.js:987:29)
    at Horseman.tryCatcher (/Users/mariobessa/Development/temp/horseman_test/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/mariobessa/Development/temp/horseman_test/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/Users/mariobessa/Development/temp/horseman_test/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromiseCtx (/Users/mariobessa/Development/temp/horseman_test/node_modules/bluebird/js/release/promise.js:604:10)
    at Async._drainQueue (/Users/mariobessa/Development/temp/horseman_test/node_modules/bluebird/js/release/async.js:138:12)
    at Async._drainQueues (/Users/mariobessa/Development/temp/horseman_test/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/Users/mariobessa/Development/temp/horseman_test/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:649:20)
    at tryOnImmediate (timers.js:622:5)
    at processImmediate [as _immediateCallback] (timers.js:594:5)`

The only difference between the example that I'm running and the one in this repository is that I'm passing PhantomJS path as as a configuration option when i'm creating a new instance of Horseman.

I'm running Node v6.9.4 on MacOS X 10.11.6 El Capitan.

Thanks in advance!

**Comment by awlayton** [comment]
It is because the Google page changed and broke the script.
