### ISSUE TITLE
.evaluate cannot be called after .switchToFrame

### ISSUE THREAD

**Issue by emmerich** [johntitus/node-horseman#268]
node-horseman: *3.2.0*
phantomjs-prebuilt: *2.1.14*

Calling `.evaluate` does not work after switching to a frame in the page.

I receive an error:
```
Unhandled rejection waitForCb
evaluatePage

global code
evaluateJavaScript@[native code]
evaluate@phantomjs://platform/webpage.js:390:39
phantomjs://code/bridge.js:121:61
    at /home/steven/dev/horseman-bug/node_modules/node-horseman/lib/actions.js:989:36
    at tryCatcher (/home/steven/dev/horseman-bug/node_modules/bluebird/js/release/util.js:16:23)
    at Function.Promise.fromNode.Promise.fromCallback (/home/steven/dev/horseman-bug/node_modules/bluebird/js/release/promise.js:180:30)
    at Horseman.<anonymous> (/home/steven/dev/horseman-bug/node_modules/node-horseman/lib/actions.js:987:29)
    at Horseman.tryCatcher (/home/steven/dev/horseman-bug/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/steven/dev/horseman-bug/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/steven/dev/horseman-bug/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromiseCtx (/home/steven/dev/horseman-bug/node_modules/bluebird/js/release/promise.js:606:10)
    at Async._drainQueue (/home/steven/dev/horseman-bug/node_modules/bluebird/js/release/async.js:138:12)
    at Async._drainQueues (/home/steven/dev/horseman-bug/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/home/steven/dev/horseman-bug/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:649:20)
    at tryOnImmediate (timers.js:622:5)
    at processImmediate [as _immediateCallback] (timers.js:594:5)
```

I believe this is because the page is not setup in the frame. Only the parent frame has the `__horseman` object, and has jQuery/Bluebird injected. I tried to add a call to `pageMaker` to `switchToFrame` but it doesn't feel right.

If you dig a little deeper you'll find that it's line 841 in `actions.js` which fails:
```javascript
__horseman.cbargs = undefined;
```
as the object `__horseman` is undefined.

Below is an example program that will demonstrate the bug. The stuff at the top is a small http server that will host a page with an iFrame. Copy it to `test.js` and put it in a directory with `node-horseman` as a dependency then run `node test.js`.

```javascript

var Horseman = require('node-horseman');
var http = require('http');

// --------------------- HTTP SERVER TO DEMONSTRATE BUG-------------------------
function handleRequest(request, response) {

  if(/frame/.test(request.url)) {
    return response.end(`<!doctype html>
    <html>
      <body>
        <div>Frame content</div>
      </body>
    </html>`)
  }

  return response.end(`<!DOCTYPE html>
    <html>
      <body>
        <div>Main frame content</div>
        <iframe src="/frame"></iframe>
      </body>
    </html>`)
}

var server = http.createServer(handleRequest);

server.listen(3070, function() {
// --------------------- END HTTP SERVER ---------------------------------------







  var horseman = new Horseman();

  horseman
    .open('http://localhost:3070/')

    // This is the main frame and works.
    .evaluate(function() {
      return document.body.innerHTML
    })
    .log()


    // After switching frame, this does not work.
    .switchToFrame(0)
    .evaluate(function() {
      return document.body.innerHTML
    })
    .close();
});

```

**Comment by awlayton** [comment]
Closing since this should be resolved by #208.

**Comment by emmerich** [comment]
Is there an issue open which aims to fix the true problem of #208? With the fixes added in #208 my code won't fail, but will jQuery be correctly injected?

**Comment by awlayton** [comment]
Evaluate won't fail, but jQuery might not be properly injected. I will make a new release with the partial fix soon.

**Comment by awlayton** [comment]
I would say #142 is address the root problem that cause the error seen in @208.
