### ISSUE TITLE
Submit form and download the server response?

### ISSUE THREAD

**Issue by mqchen** [johntitus/node-horseman#273]
Hi,
I have a case where I need to fill out a few fields and submit that form with a button-click (post). Based on that the server responds with a CSV-file that I want to save. (This is in an old ASP.NET application with some viewstate-garbage...)

Do you have any tips on how to achieve this with Horseman? Do you have anything similar to this method in revenant.js? https://github.com/jiahaog/Revenant#downloadfromclickselector-callback

When I submit the form with Horseman it crashes and throws this:

    TypeError: Cannot read property 'toString' of undefined
        at /fakepath/node_modules/node-horseman/lib/actions.js:1000:10
        at tryCatcher (/fakepath/node_modules/bluebird/js/release/util.js:16:23)
        at Function.Promise.fromNode.Promise.fromCallback (/fakepath/node_modules/bluebird/js/release/promise.js:180:30)
        at Horseman.<anonymous> (/fakepath/node_modules/node-horseman/lib/actions.js:987:29)
        at Horseman.tryCatcher (/fakepath/node_modules/bluebird/js/release/util.js:16:23)
        at Promise._settlePromiseFromHandler (/fakepath/node_modules/bluebird/js/release/promise.js:512:31)
        at Promise._settlePromise (/fakepath/node_modules/bluebird/js/release/promise.js:569:18)
        at Promise._settlePromiseCtx (/fakepath/node_modules/bluebird/js/release/promise.js:606:10)
        at Async._drainQueue (/fakepath/node_modules/bluebird/js/release/async.js:138:12)
        at Async._drainQueues (/fakepath/node_modules/bluebird/js/release/async.js:143:10)
        at Immediate.Async.drainQueues (/fakepath/node_modules/bluebird/js/release/async.js:17:14)
        at tryOnImmediate (timers.js:624:5)
        at processImmediate [as _immediateCallback] (timers.js:596:5)

Here's the code:

```javascript
horseman
  .userAgent('Mozilla/5.0 (Windows NT 6.1; WOW64; rv:27.0) Gecko/20100101 Firefox/27.0')
  .open('<url>')
  .type('input[name="ctl00$mainContent$edtUserName"]', process.env.USERNAME)
  .type('input[name="ctl00$mainContent$edtPassword"]', process.env.PASSWORD)
  .click('[name="ctl00$mainContent$btnLogin"]')
  .waitForNextPage()
  .open(`<url>`)
  .waitForSelector('#consumption-details')
  // Click on button that contains "CSV"
  .click('[value*="CSV"]')
  .waitFor(10000)
```

**Comment by awlayton** [comment]
You should not be getting an error from the code you posted. You need to figure out what `undefined` thing is having its `toString` called. Please post any additional details you can (website, output of running `DEBUG='horseman*' BLUEBIRD_DEBUG=1 node your_script.js`, etc.).

Also, horseman does not have any such function. I look briefly at the revenant function, but I could not follow it. There is a `download` function, if you can figure out the URL to download.

**Comment by mqchen** [comment]
It seems that the final `.waitFor(10000)` caused the error. By replacing it with `.waitForNextPage()` I get this error instead:

```
  horseman using PhantomJS from phantomjs module +0ms
  horseman .setup() creating phantom instance 1 +2ms
  horseman phantom created +778ms
  horseman phantom version 2.1.1 +13ms
  horseman page created +9ms
  horseman phantomjs onLoadFinished triggered success NaN +8ms
  horseman injected jQuery +20ms
  horseman .userAgent() set Mozilla/5.0 (Windows NT 6.1; WOW64; rv:27.0) Gecko/20100101 Firefox/27.0 +10ms
  horseman .open() http://www.istaonline.no/Login.aspx +1ms
  horseman phantomjs onLoadFinished triggered success 1 +2s
  horseman injected jQuery +15ms
  horseman .type() input[name="ctl00$mainContent$edtUserName"] <username> undefined +3ms
  horseman .keyboardEvent() keypress ? null +18ms
  <...>
  horseman .type() input[name="ctl00$mainContent$edtPassword"] <password> undefined +1ms
  horseman .keyboardEvent() keypress ? null +24ms
  <...>
  horseman .click() [name="ctl00$mainContent$btnLogin"] +0ms
  horseman .click() done +6ms
  horseman .waitForNextPage() +0ms
  horseman phantomjs onLoadFinished triggered success 2 +8s
  horseman jQuery not injected - already exists on page +4ms
  horseman .waitForNextPage() completed successfully +48ms
  horseman .open() http://www.istaonline.no/PopUp.aspx?Control=PopUp_Table&Metertype=HCA&cons_id=<username>&Culture=&rwndrnd= +196ms
  horseman:verbose onError NoModificationAllowedError: DOM Exception 7: An attempt was made to modify an object where modifications are not allowed.
	http://www.istaonline.no/Telerik.Web.UI.WebResource.axd?_TSM_HiddenField_=bannerContentPlaceHolder_RadScriptManagerMain_TSM&compress=1&_TSM_CombinedScripts_=%3B%3BSystem.Web.Extensions%2C+Version%3D4.0.0.0%2C+Culture%3Dneutral%2C+PublicKeyToken%3D31bf3856ad364e35%3Anb-NO%3A4bd8faf8-554d-46be-b2ff-c9d57adb612c%3Aea597d4b%3Ab25378d2%3BTelerik.Web.UI%3Anb-NO%3A9ac720df-7b88-4e1e-8026-2b8c24207e88%3A16e4e7cd%3Af7645509%3A24ee1bba%3A92fe8ea0%3Af46195d3%3Afa31b949%3A874f8ea2%3Ac128760b%3A19620875%3A490a9d4e%3Abd8f85e4%3Aed16cbdc%3A88144a7a%3Acda80b3%3A383e4ce8%3A2003d0b8%3A1e771326%3Aaa288e2d%3A258f1c72: 10826 in _removeDropDown
	http://www.istaonline.no/Telerik.Web.UI.WebResource.axd?_TSM_HiddenField_=bannerContentPlaceHolder_RadScriptManagerMain_TSM&compress=1&_TSM_CombinedScripts_=%3B%3BSystem.Web.Extensions%2C+Version%3D4.0.0.0%2C+Culture%3Dneutral%2C+PublicKeyToken%3D31bf3856ad364e35%3Anb-NO%3A4bd8faf8-554d-46be-b2ff-c9d57adb612c%3Aea597d4b%3Ab25378d2%3BTelerik.Web.UI%3Anb-NO%3A9ac720df-7b88-4e1e-8026-2b8c24207e88%3A16e4e7cd%3Af7645509%3A24ee1bba%3A92fe8ea0%3Af46195d3%3Afa31b949%3A874f8ea2%3Ac128760b%3A19620875%3A490a9d4e%3Abd8f85e4%3Aed16cbdc%3A88144a7a%3Acda80b3%3A383e4ce8%3A2003d0b8%3A1e771326%3Aaa288e2d%3A258f1c72: 9832 in dispose
	http://www.istaonline.no/Telerik.Web.UI.WebResource.axd?_TSM_HiddenField_=bannerContentPlaceHolder_RadScriptManagerMain_TSM&compress=1&_TSM_CombinedScripts_=%3B%3BSystem.Web.Extensions%2C+Version%3D4.0.0.0%2C+Culture%3Dneutral%2C+PublicKeyToken%3D31bf3856ad364e35%3Anb-NO%3A4bd8faf8-554d-46be-b2ff-c9d57adb612c%3Aea597d4b%3Ab25378d2%3BTelerik.Web.UI%3Anb-NO%3A9ac720df-7b88-4e1e-8026-2b8c24207e88%3A16e4e7cd%3Af7645509%3A24ee1bba%3A92fe8ea0%3Af46195d3%3Afa31b949%3A874f8ea2%3Ac128760b%3A19620875%3A490a9d4e%3Abd8f85e4%3Aed16cbdc%3A88144a7a%3Acda80b3%3A383e4ce8%3A2003d0b8%3A1e771326%3Aaa288e2d%3A258f1c72: 6 in dispose
	http://www.istaonline.no/Telerik.Web.UI.WebResource.axd?_TSM_HiddenField_=bannerContentPlaceHolder_RadScriptManagerMain_TSM&compress=1&_TSM_CombinedScripts_=%3B%3BSystem.Web.Extensions%2C+Version%3D4.0.0.0%2C+Culture%3Dneutral%2C+PublicKeyToken%3D31bf3856ad364e35%3Anb-NO%3A4bd8faf8-554d-46be-b2ff-c9d57adb612c%3Aea597d4b%3Ab25378d2%3BTelerik.Web.UI%3Anb-NO%3A9ac720df-7b88-4e1e-8026-2b8c24207e88%3A16e4e7cd%3Af7645509%3A24ee1bba%3A92fe8ea0%3Af46195d3%3Afa31b949%3A874f8ea2%3Ac128760b%3A19620875%3A490a9d4e%3Abd8f85e4%3Aed16cbdc%3A88144a7a%3Acda80b3%3A383e4ce8%3A2003d0b8%3A1e771326%3Aaa288e2d%3A258f1c72: 6 in _unloadHandler
	http://www.istaonline.no/Telerik.Web.UI.WebResource.axd?_TSM_HiddenField_=bannerContentPlaceHolder_RadScriptManagerMain_TSM&compress=1&_TSM_CombinedScripts_=%3B%3BSystem.Web.Extensions%2C+Version%3D4.0.0.0%2C+Culture%3Dneutral%2C+PublicKeyToken%3D31bf3856ad364e35%3Anb-NO%3A4bd8faf8-554d-46be-b2ff-c9d57adb612c%3Aea597d4b%3Ab25378d2%3BTelerik.Web.UI%3Anb-NO%3A9ac720df-7b88-4e1e-8026-2b8c24207e88%3A16e4e7cd%3Af7645509%3A24ee1bba%3A92fe8ea0%3Af46195d3%3Afa31b949%3A874f8ea2%3Ac128760b%3A19620875%3A490a9d4e%3Abd8f85e4%3Aed16cbdc%3A88144a7a%3Acda80b3%3A383e4ce8%3A2003d0b8%3A1e771326%3Aaa288e2d%3A258f1c72: 6 in <anonymous>
	http://www.istaonline.no/Telerik.Web.UI.WebResource.axd?_TSM_HiddenField_=bannerContentPlaceHolder_RadScriptManagerMain_TSM&compress=1&_TSM_CombinedScripts_=%3B%3BSystem.Web.Extensions%2C+Version%3D4.0.0.0%2C+Culture%3Dneutral%2C+PublicKeyToken%3D31bf3856ad364e35%3Anb-NO%3A4bd8faf8-554d-46be-b2ff-c9d57adb612c%3Aea597d4b%3Ab25378d2%3BTelerik.Web.UI%3Anb-NO%3A9ac720df-7b88-4e1e-8026-2b8c24207e88%3A16e4e7cd%3Af7645509%3A24ee1bba%3A92fe8ea0%3Af46195d3%3Afa31b949%3A874f8ea2%3Ac128760b%3A19620875%3A490a9d4e%3Abd8f85e4%3Aed16cbdc%3A88144a7a%3Acda80b3%3A383e4ce8%3A2003d0b8%3A1e771326%3Aaa288e2d%3A258f1c72: 6 in b 1 +5s
  horseman phantomjs onLoadFinished triggered success 3 +0ms
  horseman injected jQuery +12ms
  horseman .waitForSelector() #consumption-details +4ms
  horseman .waitFor() elementPresent #consumption-details +0ms
  horseman:verbose .waitFor() iteration elementPresent true 55 1 +61ms
  horseman .waitFor() completed successfully +0ms
  horseman .waitForSelector() complete +1ms
  horseman .click() [value*="CSV"] +0ms
  horseman .click() done +7ms
  horseman .waitForNextPage() +0ms
  horseman phantomjs onLoadFinished triggered fail 4 +7s
Unhandled rejection Error: Failed to load url
    at checkStatus (/fakepath/node_modules/node-horseman/lib/index.js:286:16)
From previous event:
    at Object.loadFinishedSetup [as onLoadFinished] (/fakepath/node_modules/node-horseman/lib/index.js:284:43)
    at /fakepath/node_modules/node-phantom-simple/node-phantom-simple.js:636:30
    at Array.forEach (native)
    at IncomingMessage.<anonymous> (/fakepath/node_modules/node-phantom-simple/node-phantom-simple.js:617:17)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

  horseman .waitForNextPage() completed successfully +2ms
  horseman .close(). +0ms
```

I suspect this happens when Horseman/Phantom tries to load the CSV file.

Do you have any tips on how I could save that file? It is only accessible by submitting a post-request. Does the `download`-method support that?

Here is the `.har` dump of the post-request (taken from Chrome).

[www.istaonline.no.har.zip](https://github.com/johntitus/node-horseman/files/893831/www.istaonline.no.har.zip)

**Comment by awlayton** [comment]
The error shown in the log is different from the error you originally posted. Has something changed?

Yes, it defaults to `GET`, but you can optionally supply a method and a request body (`download(url, path, binary, method, data)`).

Or you can just use a little JavaScript to submit the form yourself:
```javascript
horseman
    ...
    .evaluate(function sumbitForm(selector) {
        'use strict';

        return Promise.fromNode(function(done) {
	    var form = $(selector).get(0);
	    var method = (form.method || 'GET').toLowerCase();

	    $[method](form.action, $(form).serialize(), function(data) {
                return done(null, data);
            });
        });
    }, 'formSelector')
    .then(function(csvString) {
        // csvString is a string of the contents of the CSV
    })
```

**Comment by awlayton** [comment]
Sorry I missed your comment about `.waitFor(1000)`. Yes that is invalid. `waitFor` takes a function, not a number, so the original error makes sense to me now.

**Comment by mqchen** [comment]
Thank you for the tip! That's a really good idea to submit the request using ajax within the browser instead of simulating a request with node.

After some fiddling with "magic" ASP.NET fields (`__EVENTTARGET`) I ended up with this code:

```javascript
  .evaluate(function(done) {
    'use strict';

    var form = document.querySelector('#form1');
    var method = (form.method || 'POST').toLowerCase();
    var csvButtonName = document.querySelector('[value*="CSV"]').getAttribute('name');

    document.querySelector('[name="__EVENTTARGET"]').setAttribute('value', csvButtonName);

    $[method](form.action, $(form).serialize(), function(data) {
      return done(null, data);
    });
  })
```
