### ISSUE TITLE
horseman error: TypeError: callback is not a function

### ISSUE THREAD

**Issue by webdev** [johntitus/node-horseman#276]
I am using `async` package with `horseman`, but getting the error `TypeError: callback is not a function`.

My code looks like as follows
```
   function extractProductUrls(pageUrl, callback) {
     horseman
    .userAgent('Mozilla/5.0 (Windows NT 6.1; WOW64; rv:27.0) Gecko/20100101 Firefox/27.0')
    .wait(500)
    .open(page.url)
    .html()
    .then(function(data){   
    ...
    callback(null, product.name); // This is where it errors out
    }
  }
....
   async.mapLimit(results, 1, function(pageUrl, callback) { 
     extractProductUrls(pageUrl, callback);
   });
```

What am I doing wrong? Why is `callback` not a function?

**Comment by robertpallas** [comment]
Task has nothing to do with Horseman.

I would use `mapSeries` and make sure `results` is iterable first.

Start with
`async.mapSeries(results, extractProductUrls);` 

If that does not help simplify `async` flow and post more code, will try help you out.

**Comment by webdev** [comment]
Ok, I changed `mapSeries` to `async.mapSeries` like you suggested, so it looks like this. Still getting `TypeError: callback is not a function` pretty regularly with this stacktrace

```
Unhandled rejection TypeError: callback is not a function
    at /Users/dev/workspace/prj/node_modules/async/lib/async.js:232:15
    at /Users/dev/workspace/prj/node_modules/async/lib/async.js:142:25
    at /Users/dev/workspace/prj/node_modules/async/lib/async.js:229:17
    at Horseman.<anonymous> (/Users/dev/workspace/prj/links_miner.js:70:7) (This is where I am calling callback method)
    at Horseman.tryCatcher (/Users/dev/workspace/prj/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/dev/workspace/prj/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/dev/workspace/prj/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/dev/workspace/prj/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/dev/workspace/prj/node_modules/bluebird/js/release/promise.js:689:18)
    at Async._drainQueue (/Users/dev/workspace/prj/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/dev/workspace/prj/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/Users/dev/workspace/prj/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:666:20)
    at tryOnImmediate (timers.js:639:5)
    at processImmediate [as _immediateCallback] (timers.js:611:5)
```

```
  function extractProductUrls(page, callback) {  
  var horseman = new Horseman();
  
  horseman
  .userAgent('Mozilla/5.0 (Windows NT 6.1; WOW64; rv:27.0) Gecko/20100101 Firefox/27.0')
  .wait(500)
  .open(page.url)
  .html()
  .then(function(data){        
    $ = cheerio.load(data);
    
    var $ = cheerio.load(data);
  
    var products = $("div.itemWrapper");
  
    products.each(function(index) {    
      // record products

      callback(null, product.name);
    });
  })
  .catch(function(e){
    callback();      
    console.log("horseman error: "+e)
    this.close()
  })
  
  horseman.on('resourceError',function(err)  {
    console.log(err);
  });
}  

  pool.query('SELECT * FROM categories"', function (error, results, fields) {
    if (error) throw error;
    async.mapSeries(results, linksMiner.extractProductUrls);
  });
```

**Comment by webdev** [comment]
I think I got it, thanks!

**Comment by awlayton** [comment]
FYI, you can just use [`.mapSeries()`](http://bluebirdjs.com/docs/api/mapseries.html) etc. in Horseman chains.
