### ISSUE TITLE
 Unhandled rejection Error: jQuery injection failed

### ISSUE THREAD

**Issue by MrBlueBird** [johntitus/node-horseman#277]
`0|app      | Unhandled rejection Error: jQuery injection failed
0|app      |     at /var/www/html/node/node_modules/node-horseman/lib/index.js:313:18
0|app      |     at PassThroughHandlerContext.finallyHandler (/var/www/html/node/node_modules/node-horseman/node_modules/bluebird/js/release/finally.js:56:23)
0|app      |     at PassThroughHandlerContext.tryCatcher (/var/www/html/node/node_modules/node-horseman/node_modules/bluebird/js/release/util.js:16:23)
0|app      |     at Promise._settlePromiseFromHandler (/var/www/html/node/node_modules/node-horseman/node_modules/bluebird/js/release/promise.js:510:31)
0|app      |     at Promise._settlePromise (/var/www/html/node/node_modules/node-horseman/node_modules/bluebird/js/release/promise.js:567:18)
0|app      |     at Promise._settlePromise0 (/var/www/html/node/node_modules/node-horseman/node_modules/bluebird/js/release/promise.js:612:10)
0|app      |     at Promise._settlePromises (/var/www/html/node/node_modules/node-horseman/node_modules/bluebird/js/release/promise.js:691:18)
0|app      |     at Promise._fulfill (/var/www/html/node/node_modules/node-horseman/node_modules/bluebird/js/release/promise.js:636:18)
0|app      |     at /var/www/html/node/node_modules/node-horseman/node_modules/bluebird/js/release/nodeback.js:42:21
0|app      |     at /var/www/html/node/node_modules/node-horseman/node_modules/node-phantom-simple/node-phantom-simple.js:60:18
0|app      |     at poll_func (/var/www/html/node/node_modules/node-horseman/node_modules/node-phantom-simple/node-phantom-simple.js:589:7)
0|app      |     at /var/www/html/node/node_modules/node-horseman/node_modules/node-phantom-simple/node-phantom-simple.js:52:7
0|app      |     at IncomingMessage.<anonymous> (/var/www/html/node/node_modules/node-horseman/node_modules/node-phantom-simple/node-phantom-simple.js:478:13)
0|app      |     at IncomingMessage.emit (events.js:117:20)
0|app      |     at _stream_readable.js:929:16
0|app      |     at process._tickDomainCallback [as _tickCallback] (node.js:463:13)
0|app      | Unhandled rejection Error: jQuery injection failed
0|app      |     at /var/www/html/node/node_modules/node-horseman/lib/index.js:313:18
0|app      |     at PassThroughHandlerContext.finallyHandler (/var/www/html/node/node_modules/node-horseman/node_modules/bluebird/js/release/finally.js:56:23)
0|app      |     at PassThroughHandlerContext.tryCatcher (/var/www/html/node/node_modules/node-horseman/node_modules/bluebird/js/release/util.js:16:23)
0|app      |     at Promise._settlePromiseFromHandler (/var/www/html/node/node_modules/node-horseman/node_modules/bluebird/js/release/promise.js:510:31)
0|app      |     at Promise._settlePromise (/var/www/html/node/node_modules/node-horseman/node_modules/bluebird/js/release/promise.js:567:18)
0|app      |     at Promise._settlePromise0 (/var/www/html/node/node_modules/node-horseman/node_modules/bluebird/js/release/promise.js:612:10)
0|app      |     at Promise._settlePromises (/var/www/html/node/node_modules/node-horseman/node_modules/bluebird/js/release/promise.js:691:18)
0|app      |     at Promise._fulfill (/var/www/html/node/node_modules/node-horseman/node_modules/bluebird/js/release/promise.js:636:18)
0|app      |     at /var/www/html/node/node_modules/node-horseman/node_modules/bluebird/js/release/nodeback.js:42:21
0|app      |     at /var/www/html/node/node_modules/node-horseman/node_modules/node-phantom-simple/node-phantom-simple.js:60:18
0|app      |     at IncomingMessage.<anonymous> (/var/www/html/node/node_modules/node-horseman/node_modules/node-phantom-simple/node-phantom-simple.js:645:9)
0|app      |     at IncomingMessage.emit (events.js:117:20)
0|app      |     at _stream_readable.js:929:16
0|app      |     at process._tickDomainCallback [as _tickCallback] (node.js:463:13)`

if use .wait(5000) Is received this errors. What is wrong?

**Comment by awlayton** [comment]
Please reproduce with `DEBUG='horman*'` and `BLUEBIRD_DEBUG=1` set. The log is not too helpful without them.

Also, post the code and url if you can. Just knowing you called `.wait(5000)` is not enough to go on.
