### ISSUE TITLE
Horseman crashes when more than 11 instances are running

### ISSUE THREAD

**Issue by jpvi** [johntitus/node-horseman#28]
I'm writing code that uses the async library that does web spidering. I've tried opening just 1 site at a time and the code runs without a hitch. I ran into this while trying to use node-horseman:

(node) warning: possible EventEmitter memory leak detected. 11 SIGINT listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at process.addListener (events.js:179:15)
    at process.on.process.addListener (node.js:668:26)
    at /app/node_modules/node-horseman/node_modules/node-phantom-simple/node-phantom simple.js:87:21
    at Array.forEach (native)
    at spawnPhantom (/app/node_modules/node-horseman/node_modules/node-phantom-simple/node-phantom-simple.js:86:31)
    at Object.exports.create (/app/node_modules/node-horseman/node_modules/node-phantom-simple/node-phantom-simple.js:201:5)
    at new Horseman (/app/node_modules/node-horseman/lib/index.js:135:11)

**Comment by johntitus** [comment]
Have you googled `emitter.setMaxListeners()`?

**Comment by johntitus** [comment]
Closing due to lack of info.
