### ISSUE TITLE
Can't get proxy to work, works otherwise

### ISSUE THREAD

**Issue by 3zzy** [johntitus/node-horseman#281]
I'm using Crawlera proxy for this quick test, but it just doesn't work. The proxy works (tried with cURL) and horseman works without the proxy (screenshot image confirms it).

This is the debug log:
`➜  root: DEBUG='horseman' node scrape-google-shopping.js
  horseman using PhantomJS from phantomjs-prebuilt module +0ms
  horseman .setup() creating phantom instance 1 +269ms
  horseman Horseman option load-images overridden by phantomOptions +5ms
  horseman Horseman option ssl-protocol overridden by phantomOptions +0ms
  horseman phantom created +195ms
  horseman phantom version 2.1.1 +29ms
  horseman page created +14ms
  horseman phantomjs onLoadFinished triggered success NaN +13ms
  horseman injected jQuery +30ms
  horseman .open() http://atomurl.net/myip/ +5ms
  horseman phantomjs onLoadFinished triggered success 1 +789ms
  horseman injected jQuery +26ms
  horseman .waitForSelector() #isp undefined +5ms
  horseman .waitFor() elementPresent #isp +1ms
  horseman .waitFor() timed out +10s
  horseman .close(). +7ms
Unhandled rejection TimeoutError: timeout during .waitFor() after 10038 ms
    at Timeout.waitForCheck (/var/www/html/mywebsite.com/public_html/app/node_modules/node-horseman/lib/actions.js:1688:13)
    at ontimeout (timers.js:380:14)
    at tryOnTimeout (timers.js:244:5)
    at Timer.listOnTimeout (timers.js:214:5)

➜  root:`

**Comment by awlayton** [comment]
Have you tried setting the `proxyType` option?

**Comment by 3zzy** [comment]
Yes, tried with that first.

**Comment by awlayton** [comment]
The `phantomOptions` argument is more of an advanced feature that can break stuff. You should try using the normal Horseman options instead. Everything you are specifying is supported by normal Horseman.

**Comment by awlayton** [comment]
Also, I recommend explicitly setting `proxyType` to `'http'`, or whatever the correct type is, as I am not sure what it defaults to.

**Comment by nigelalford** [comment]
This may or may not help, I had problems with this too and had just adding a string of the url and port fails, BUT prepending `'//'` the url in the `proxy` key resolved my issue

**Comment by SacDin** [comment]
Having same issue
