### ISSUE TITLE
Unhandled rejection Error  on trying to create a horseman instance

### ISSUE THREAD

**Issue by AkshatShetty101** [johntitus/node-horseman#298]
Code:
  var horseman = new Horseman({timeout:3000,interval:20});
  horseman
        .open('http://services.ecourts.gov.in/ecourtindia_v5/')
        .catch(function(err){
            console.log(err);
            return false;
        })
        .then(function(data){
            console.log(data);
            if(data===false)
                response.send({"status":"-1"});
            else
                response.send({"status":"1"});
            horseman.close();
        })

Error received:
Unhandled rejection Error
    at ChildProcess.immediateExit (/root/mean_stack/Ecourt/node_modules/node-phantom-simple/node-phantom-simple.js:153:23)
    at Object.onceWrapper (events.js:318:30)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:197:12)

I have used the same code on my windows 10 pc however when i shifted to my  Ubuntu 16.04.2 LTS one it gives this error each time I try to use node-horseman. Please help. Thanks in advance.

Node version-v8.1.3
npm version-5.1.0

**Comment by AkshatShetty101** [comment]
My phantomjs path was not properly defined so i was facing this issue.
