### ISSUE TITLE
spawn phantomjs ENOENT

### ISSUE THREAD

**Issue by afang** [johntitus/node-horseman#62]
What does this mean?

```
Unhandled rejection Error: spawn phantomjs ENOENT
    at exports._errnoException (util.js:746:11)
    at Process.ChildProcess._handle.onexit (child_process.js:1053:32)
    at child_process.js:1144:20
    at process._tickCallback (node.js:355:11)
    at Function.Module.runMain (module.js:503:11)
    at startup (node.js:129:16)
    at node.js:814:3
```

I'm using the example code below:

```
var Horseman = require("node-horseman");
var horseman = new Horseman();

horseman
.open('http://lite.yelp.com/search?find_desc=pizza&find_loc=94040&find_submit=Search')
.text('address')
.then(function(address){
	console.log(address);
	horseman.close();
});
```

**Comment by awlayton** [comment]
Do you have phantom installed?

**Comment by johntitus** [comment]
Closing. Assuming @awlayton was right.
