### ISSUE TITLE
install new node-horseman in window problem?

### ISSUE THREAD

**Issue by SinhVienDHQG** [johntitus/node-horseman#70]
I think there is error when install new version on window cause by buebird version?
C:\nodejs>node main.js

C:\nodejs>npm install node-horseman
node-horseman@2.8.0 node_modules\node-horseman
├── clone@0.1.19
├── defaults@1.0.3 (clone@1.0.2)
├── node-phantom-simple@2.1.0
├── bluebird@2.10.2
└── debug@2.2.0 (ms@0.7.1)

C:\nodejs>node main.js
Unhandled rejection TypeError: Cannot read property 'exit' of undefined
    at null.<anonymous> (C:\nodejs\node_modules\node-horseman\lib\index.js:178:2
2)
    at Object.finallyHandler (C:\nodejs\node_modules\node-horseman\node_modules\
bluebird\js\main\finally.js:38:31)
    at Object.tryCatcher (C:\nodejs\node_modules\node-horseman\node_modules\blue
bird\js\main\util.js:26:23)
    at Promise._settlePromiseFromHandler (C:\nodejs\node_modules\node-horseman\n
ode_modules\bluebird\js\main\promise.js:507:31)
    at Promise._settlePromiseAt (C:\nodejs\node_modules\node-horseman\node_modul
es\bluebird\js\main\promise.js:581:18)
    at Async._drainQueue (C:\nodejs\node_modules\node-horseman\node_modules\blue
bird\js\main\async.js:128:12)
    at Async._drainQueues (C:\nodejs\node_modules\node-horseman\node_modules\blu
ebird\js\main\async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\nodejs\node_modules\nod
e-horseman\node_modules\bluebird\js\main\async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:368:17)

C:\nodejs>

**Comment by awlayton** [comment]
What is in the file main.js?

**Comment by SinhVienDHQG** [comment]
Just simple example from readme:

var Horseman = require('node-horseman');
var horseman = new Horseman();

horseman
.userAgent("Mozilla/5.0 (Windows NT 6.1; WOW64; rv:27.0) Gecko/20100101 Firefox/27.0")
.open('https://www.facebook.com')
.type('input[id="email"]', 'notebook102015@gmail.com')
.type('input[id="pass"]', 'Hanoi123')
.click('label[id="loginbutton"]')
.waitForNextPage()
.text('div[id="pagelet_bluebar"]')
.log() // prints out the number of results
.screenshot('C:/nodejs/home.png')
.close();

**Comment by awlayton** [comment]
Hm, it works for me in Linux.

Can you do `set BLUEBIRD_DEBUG=1` and then run it again and post the output? That should make the stack trace more helpful.

**Comment by awlayton** [comment]
@SinhVienDHQG I think your problem is you don't have PhantomJS installed (or on your path). It works for me in Windows with the module versions you have.

**Comment by SinhVienDHQG** [comment]
After set BLUEBIRD_DEBUG=1 (i type it in cmd), then run node main.js:

Unhandled rejection TypeError: Cannot read property 'exit' of undefined
    at null.<anonymous> (c:\nodejs\node-horseman\node_modules\node-horseman\lib\
index.js:178:22)
From previous event:
    at Horseman.close (c:\nodejs\node-horseman\node_modules\node-horseman\lib\in
dex.js:177:27)
    at null.<anonymous> (c:\nodejs\node-horseman\node_modules\node-horseman\lib\
index.js:183:15)
    at processImmediate [as _immediateCallback] (timers.js:368:17)
From previous event:
    at Promise.HorsemanPromise.close (c:\nodejs\node-horseman\node_modules\node-
horseman\lib\index.js:182:21)
    at Object.<anonymous> (c:\nodejs\node-horseman\main.js:13:4)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:134:18)
    at node.js:961:3

c:\nodejs\node-horseman>

**Comment by SinhVienDHQG** [comment]
About phantomjs, i have it on path:


c:\nodejs\node-horseman>phantomjs --version
1.9.8

c:\nodejs\node-horseman>

**Comment by johntitus** [comment]
Do you have any aversion to upgrading to Phantom 2.0?

**Comment by awlayton** [comment]
Strange, I got that exact stack trace when I removed phantomjs from the path. I have PhantomJS 2.0 though, so yeah upgrading might help.

**Comment by awlayton** [comment]
I got that error when I switched it to Phantom 1.9.8, so upgrading fixes the problem. However, it should probably work with the older phantomjs too...

**Comment by awlayton** [comment]
Actually, 1.9.8 works too now. Where it was it wasn't being found by the node process (even though other things could find it), but I moved it and now it works. How did you install PhantomJS?

**Comment by SinhVienDHQG** [comment]
I use: npm install -g phantomjs

**Comment by awlayton** [comment]
Yeah it doesn't work with that. It seems that what gets put on the PATH isn't the actual PhantomJS executable. The thing on the path is some sort of script and it doesn't work with horseman for some reason.

**Comment by SinhVienDHQG** [comment]
Ah, so i manual download phantomjs 2.0 and add bin folder to PATH, then : npm uninstall -g phantomjs.
And now it works! Thank so much for your help!

**Comment by awlayton** [comment]
@SinhVienDHQG You should be able to use horseman with the npm phantomjs like so:
```javascript
var phantomjs = require('phantomjs');

var horseman = new Horseman({phantomPath: phantomjs.path});
```
That will point horseman to where the actual PhantomJS binary is.
